### ISSUE TITLE
Model forecasting with new environment

### ISSUE THREAD

**Issue by sylvainschmitt** [sylvainschmitt/SSDM#10]
Following several demands we need to add the possibility of model forecasting inside the package with a different environment than the one used to build the SDM. For instance, it will allow to model the future distribution of a a species under climate change.

**Comment by sylvainschmitt** [comment]
In fact, it is already possible only by changing the environment used in projection with the internal function `project`. Consequently the only current issue is that the `project` function is not available to the user. Anyway their is a work around to use it, see the minimal example below.

```
library(SSDM)
data(Env)
data(Occurrences)
Occurrences <- subset(Occurrences, Occurrences$SPECIES == 'elliptica')
SDM <- modelling('GLM', Occurrences, Env, Xcol = 'LONGITUDE', Ycol = 'LATITUDE')
plot(SDM@projection)
Env2 <- raster::stack(Env-1)
project_internal <- function(x, y) project(x, y)
environment(project_internal) <- asNamespace("SSDM")
SDM2 <- project_internal(SDM, Env2)
plot(SDM2@projection)
```

This is only a temporary solution, and a true implementation of model forecasting inside the package should be realized.

**Comment by fernandezmiguel** [comment]
Dear Sylvain, thank you very much for all your efforts creating this package! We are already using it extensively in Bolivia. We were wondering if the proposed suggestion that you have as a workaround to project the species distribution into a different scenario works with ensemble models? We try your suggestion with one model and it works but when trying to apply the same solution with an ensemble we get the following error: Error in (function (classes, fdef, mtable) : unable to find an inherited method for function ‘project’ for signature ‘"Ensemble.SDM"’
Any guidance will be much appreciated!
Miguel

**Comment by fernandezmiguel** [comment]
Dear Sylvain,
We just realized that the current project only works with individual models and not for ensembles. Anyway we are now at a stage where we are using project for individual models, however when in the code we point to two different folders with two different sets of environmental variables the models from the current conditions and the projected conditions are identical, see code below:
`library(SSDM)
Env_p <- load_var(path = "G:/Bolivia_SDMs/Climate/Present_test", files = NULL, format = c(".tif"), categorical = NULL,
                  Norm = FALSE, tmp = TRUE, verbose = TRUE, GUI = FALSE)
Env_f <- load_var(path = "G:/Bolivia_SDMs/Climate/Future_test", files = NULL, format = c(".tif"), categorical = NULL,
                  Norm = FALSE, tmp = TRUE, verbose = TRUE, GUI = FALSE)
## Definir varaible con las observaciones
setwd("G:/Bolivia_SDMs/Obs")
Occ <- load_occ(path = getwd(), Env_p, file="bradypus.csv", header = TRUE, sep = ",",
                Xcol = "long", Ycol = "lat", Spcol = "species")
 SDM <- modelling('SVM', Occ, Env_p, Xcol = 'long', Ycol = 'lat')
plot(SDM@projection, main = "present")
 
project_internal <- function(x, y) project(x, y)
environment(project_internal) <- asNamespace("SSDM")
SDM2 <- project_internal(SDM, Env_f)
plot(SDM2@projection, main = "future")`
 
We double check if the variables are indeed different. Still the results are identical. Any suggestions?

**Comment by sylvainschmitt** [comment]
Dear Miguel,

First as you realized model forecasting with project function is only available for SDM and not ESDM. In fact that's not completely true. I did not made it available initially for SDM but you can hack it using the internal function project (that you can also call this way SSDM:::project()). And that's why it's not integrated to the full architecture of SSDM package. Because we could imagine a project function for ESDM level. But that would imply to recalculate projection for every SDM and re-assemble each individual forecast SDM in one forecast ESDM. In further development on SSDM we need to take that into account, but as you can see model forecasting to ESDM and SSDM is not straightforward. In the meantime what you can do is to realize an ESDM. Then you can project in a new environment each SDM and re-assemble them. Test the following code but it should look like something this way:
```
ESDM <- ensemble_modelling("algos", Occ, Env, ...)
project_internal <- function(x, y) project(x, y)
environment(project_internal) <- asNamespace("SSDM")
SDMs_forecast <- lapply(ESDM@enms, function(sdm) project_internal(sdm, Env_forecast))
ESDM_forecast <- do.call("ensemble", SDMs_forecast)
```

**Comment by fernandezmiguel** [comment]
Dear Sylvain,
THANK YOU very much for your prompt response. 
We use the example code you provided with the test data and indeed it worked fine. However when we point Env2 into a different folder (instead of Env-1) with different variables the results from both the current and the projected models are identical.
We wonder if the variables that we are using are the problem. For this we tested the model using Maxent GUI and the results are different. We are a puzzled...
Not sure what to do.
Any advice?

**Comment by sylvainschmitt** [comment]
Ok that's interesting because it sounds like a bug to fix !

So with two different environmental data set (Env1 and Env2) from two different folders you have the same projections with SVM but not with Maxent ?

Could you try to produce a minimal example for me ? You could save the default `data(Env)` and `data(Env+1)` into to temporary folder and then write a basic example for me to reproduce the bug.

**Comment by fernandezmiguel** [comment]
To be even more precise. We have two env. datasets in two different folders (e.g., present and future). We run Maxent inside SSDM-R and use project and the results are identical. 
We run the Java Maxent application outside R and using these datasets and the models are different.

**Comment by sylvainschmitt** [comment]
You mean that with Maxent you trained you model only on present environment and you did projection on the present and future environment ? Because if not it's completely normal. And if you did that's strange because SSDM calls Maxent itself, it might be an issue with the call to project using Maxent. Once again please try to furnish a minimal example for further help.

**Comment by fernandezmiguel** [comment]
I think we found the issue. we were using tmp=TRUE when defining the variables, we change to false and the results are now as expected (i.e., different):

`Env_f <- load_var(path = "G:/Bolivia_SDMs/Climate/Future_test", files = NULL, format = c(".tif"), categorical = NULL,
                  Norm = FALSE, tmp = FALSE, verbose = TRUE, GUI = FALSE)`

`Env_f <- load_var(path = "G:/Bolivia_SDMs/Climate/Future_test", files = NULL, format = c(".tif"), categorical = NULL,
                  Norm = FALSE, tmp = TRUE, verbose = TRUE, GUI = FALSE)`

**Comment by sylvainschmitt** [comment]
Ok that's perfectly normal, I'm sorry ! My dirty hack to do model forecasting with current SSDM architecture won't work with Maxent. Because Maxent use both the environmental information to produce the model and the projection, so when you are using back project with a new environment with Maxent in SSDM it recompute the fit before the projection. Have a look to [project method](https://github.com/sylvainschmitt/SSDM/blob/master/R/project.R).

**Comment by fernandezmiguel** [comment]
THANK YOU, it is amazing when a package developer is so responsive!!! 
We are extremely grateful!
Miguel

**Comment by sylvainschmitt** [comment]
Ok so that's working with SVM when you don't use the tmp option ? There might be an issue with temporary file overriding themselves. Thank you for spotting the bug.

**Comment by sylvainschmitt** [comment]
Ok looking into the code itself I think it's due to the fact that you variable names in the two environment are exactly the same besides the stacks have different names. And the code is using the names of the variable and not of the stack to write the temporary file.

https://github.com/sylvainschmitt/SSDM/blob/f10c2c9302941e5abba0238032b0642d71ebe318/R/load_var.R#L173-L179

A fix will be to add the stack name in the name of the temporary file or even the system date in case someone is using stack with similar names. I will add it in my to do list unless you have the courage to implement it and do a pull request ! In the meantime if you want to use the temporary option just rename your variables files differently.

**Comment by sylvainschmitt** [comment]
Because the issue it totally different I re-open a new one #31

**Comment by asierrl** [comment]
Dear Sylvain.
First of all, thanks a lot for your hard work and usefull tool, Thanks for sharing!!
Above you suggest a workaround to get predictions on new environments for ensemble models: 

>In the meantime what you can do is to realize an ESDM. Then you can project in a new environment each SDM and re-assemble them. Test the following code but it should look like something this way:
> 
> ```
> ESDM <- ensemble_modelling("algos", Occ, Env, ...)
> project_internal <- function(x, y) project(x, y)
> environment(project_internal) <- asNamespace("SSDM")
> SDMs_forecast <- lapply(ESDM@enms, function(sdm) project_internal(sdm, Env_forecast))
> ESDM_forecast <- do.call("ensemble", SDMs_forecast)
> ```

I don't fully understand the approach, as my knowledge of R functions and packages is still limited. However, I tried to reproduce your code with the Occurrences and Env data and cannot find any enms slot for ensemble models. Am I loosing something? Is there a similar slot with different name that I could use instead?
Thanks a lot, best regards,
Asier

**Comment by sylvainschmitt** [comment]
First of all, I recently discovered that instead of writing:
> ```
> project_internal <- function(x, y) project(x, y)
> environment(project_internal) <- asNamespace("SSDM")
>```
You can directly call an internal function this way:
> ```
> SSDM:::project(x,y)
>```
But effectively, if you are not used to package development the concept of internal function can be a bit blur (I recommend Hadley Wickham book on R package if you want to better understand it). Anyway, you can still perform it even if you don't full understand what an internal function is (basically a function I did not opened to the user but I kept inside the package). So if I understood well your issue is that when you take your ensemble models you don't have any enms ? It means either that you badly called  the slot or that you ESDM is empty due to maybe to restrictive evaluation rules (and if it's the case the package should have told you it's the case). Try:
 ```
 Your_ESDM_name@enms
```
And if it's empty check the output of:
 ```
 str(Your_ESDM_name)
```
best,
Sylvain

**Comment by asierrl** [comment]
Thanks for your response, Sylvain.
I tried both my.model@enms and str(my.model). My.model@enms results in an
incorrect slot message, while I did not find any enms slot in
str(my.model). I thoughtbthat perhaps in newest versions enms was changed
to a different names, but I didn't find any similar slot.
Odd enough, the models don't seem to be empty, I get correct values for
evaluation, algorithm evaluation and correlation, variable inportance and
others, including projrction, binary and uncertainty.
I am now out for a couple of days but I'll send the output of str(my.model)
as faras I am back.
Best regards.
Asier


O luns, 26 nov, 2018 20:55, Sylvain SCHMITT <notifications@github.com>
escribiu:

**Comment by asierrl** [comment]
Hi, Sylvain.
I'm back again.
I tried again with an ensemble model I did last week. The model seems to be
Ok, I have algorithm correlation and evaluation, variable importance and
all the remaining staff, including probability, binary and uncertainty map.
However, when I try my.model@enms I get this message:

Error: no slot of name "enms" for this object of class "Ensemble.SDM"

Below I copy the output of str(my.model) for you.

Best regards.

Asier


str(my.model)Formal class 'Ensemble.SDM' [package "SSDM"] with 10 slots
  ..@ uncertainty          :Formal class 'RasterLayer' [package
"raster"] with 12 slots
  .. .. ..@ file    :Formal class '.RasterFile' [package "raster"] with 13 slots
  .. .. .. .. ..@ name        : chr
"E:\\Activos\\Amalia\\R\\Analisis\\Resultados\\CF\\Cf_ensemble.tif\\Rasters\\uncertainty.tif"
  .. .. .. .. ..@ datanotation: chr "FLT4S"
  .. .. .. .. ..@ byteorder   : chr "little"
  .. .. .. .. ..@ nodatavalue : num -Inf
  .. .. .. .. ..@ NAchanged   : logi FALSE
  .. .. .. .. ..@ nbands      : int 1
  .. .. .. .. ..@ bandorder   : chr "BIL"
  .. .. .. .. ..@ offset      : int 0
  .. .. .. .. ..@ toptobottom : logi TRUE
  .. .. .. .. ..@ blockrows   : int 1
  .. .. .. .. ..@ blockcols   : int 1945
  .. .. .. .. ..@ driver      : chr "gdal"
  .. .. .. .. ..@ open        : logi FALSE
  .. .. ..@ data    :Formal class '.SingleLayerData' [package
"raster"] with 13 slots
  .. .. .. .. ..@ values    : logi(0)
  .. .. .. .. ..@ offset    : num 0
  .. .. .. .. ..@ gain      : num 1
  .. .. .. .. ..@ inmemory  : logi FALSE
  .. .. .. .. ..@ fromdisk  : logi TRUE
  .. .. .. .. ..@ isfactor  : logi FALSE
  .. .. .. .. ..@ attributes: list()
  .. .. .. .. ..@ haveminmax: logi TRUE
  .. .. .. .. ..@ min       : num 5.7e-09
  .. .. .. .. ..@ max       : num 0.196
  .. .. .. .. ..@ band      : int 1
  .. .. .. .. ..@ unit      : chr ""
  .. .. .. .. ..@ names     : chr "uncertainty"
  .. .. ..@ legend  :Formal class '.RasterLegend' [package "raster"]
with 5 slots
  .. .. .. .. ..@ type      : chr(0)
  .. .. .. .. ..@ values    : logi(0)
  .. .. .. .. ..@ color     : logi(0)
  .. .. .. .. ..@ names     : logi(0)
  .. .. .. .. ..@ colortable: logi(0)
  .. .. ..@ title   : chr(0)
  .. .. ..@ extent  :Formal class 'Extent' [package "raster"] with 4 slots
  .. .. .. .. ..@ xmin: num -9.56
  .. .. .. .. ..@ xmax: num -5.5
  .. .. .. .. ..@ ymin: num 38.9
  .. .. .. .. ..@ ymax: num 43.8
  .. .. ..@ rotated : logi FALSE
  .. .. ..@ rotation:Formal class '.Rotation' [package "raster"] with 2 slots
  .. .. .. .. ..@ geotrans: num(0)
  .. .. .. .. ..@ transfun:function ()
  .. .. ..@ ncols   : int 1945
  .. .. ..@ nrows   : int 2364
  .. .. ..@ crs     :Formal class 'CRS' [package "sp"] with 1 slot
  .. .. .. .. ..@ projargs: chr "+proj=longlat +datum=WGS84 +no_defs
+ellps=WGS84 +towgs84=0,0,0"
  .. .. ..@ history : list()
  .. .. ..@ z       : list()
  ..@ algorithm.correlation:'data.frame':	8 obs. of  8 variables:
  .. ..$ C.fragile.GLM.SDM.ensemble : num [1:8] 1 0.294 0.576 0.737 0.42 ...
  .. ..$ C.fragile.GAM.SDM.ensemble : num [1:8] 0.294 1 0.621 0.247 0.525 ...
  .. ..$ C.fragile.RF.SDM.ensemble  : num [1:8] 0.576 0.621 1 0.542 0.813 ...
  .. ..$ C.fragile.MARS.SDM.ensemble: num [1:8] 0.737 0.247 0.542 1 0.477 ...
  .. ..$ C.fragile.CTA.SDM.ensemble : num [1:8] 0.42 0.525 0.813 0.477 1 ...
  .. ..$ C.fragile.ANN.SDM.ensemble : num [1:8] 0.579 0.587 0.875
0.622 0.732 ...
  .. ..$ C.fragile.SVM.SDM.ensemble : num [1:8] 0.551 0.618 0.76 0.545 0.628 ...
  .. ..$ C.fragile.GBM.SDM.ensemble : num [1:8] 0.442 0.426 0.644 0.46 0.55 ...
  ..@ algorithm.evaluation :'data.frame':	8 obs. of  8 variables:
  .. ..$ threshold    : num [1:8] 0.463 0.571 0.338 0.449 0.834 ...
  .. ..$ AUC          : num [1:8] 0.772 0.822 0.882 0.815 0.844 ...
  .. ..$ omission.rate: num [1:8] 0.24 0.26 0.14 0.22 0.28 0.296 0.12 0.42
  .. ..$ sensitivity  : num [1:8] 0.76 0.74 0.86 0.78 0.72 0.704 0.88 0.58
  .. ..$ specificity  : num [1:8] 0.785 0.903 0.903 0.849 0.968 ...
  .. ..$ prop.correct : num [1:8] 0.776 0.846 0.888 0.825 0.881 ...
  .. ..$ Kappa        : num [1:8] 0.526 0.655 0.756 0.621 0.725 ...
  .. ..$ kept.model   : int [1:8] 10 10 10 10 10 10 10 9
  ..@ name                 : chr "C fragile.Ensemble.SDM"
  ..@ projection           :Formal class 'RasterLayer' [package
"raster"] with 12 slots
  .. .. ..@ file    :Formal class '.RasterFile' [package "raster"] with 13 slots
  .. .. .. .. ..@ name        : chr
"E:\\Activos\\Amalia\\R\\Analisis\\Resultados\\CF\\Cf_ensemble.tif\\Rasters\\Probability.tif"
  .. .. .. .. ..@ datanotation: chr "FLT4S"
  .. .. .. .. ..@ byteorder   : chr "little"
  .. .. .. .. ..@ nodatavalue : num -Inf
  .. .. .. .. ..@ NAchanged   : logi FALSE
  .. .. .. .. ..@ nbands      : int 1
  .. .. .. .. ..@ bandorder   : chr "BIL"
  .. .. .. .. ..@ offset      : int 0
  .. .. .. .. ..@ toptobottom : logi TRUE
  .. .. .. .. ..@ blockrows   : int 1
  .. .. .. .. ..@ blockcols   : int 1945
  .. .. .. .. ..@ driver      : chr "gdal"
  .. .. .. .. ..@ open        : logi FALSE
  .. .. ..@ data    :Formal class '.SingleLayerData' [package
"raster"] with 13 slots
  .. .. .. .. ..@ values    : logi(0)
  .. .. .. .. ..@ offset    : num 0
  .. .. .. .. ..@ gain      : num 1
  .. .. .. .. ..@ inmemory  : logi FALSE
  .. .. .. .. ..@ fromdisk  : logi TRUE
  .. .. .. .. ..@ isfactor  : logi FALSE
  .. .. .. .. ..@ attributes: list()
  .. .. .. .. ..@ haveminmax: logi TRUE
  .. .. .. .. ..@ min       : num 2.69e-05
  .. .. .. .. ..@ max       : num 0.787
  .. .. .. .. ..@ band      : int 1
  .. .. .. .. ..@ unit      : chr ""
  .. .. .. .. ..@ names     : chr "Probability"
  .. .. ..@ legend  :Formal class '.RasterLegend' [package "raster"]
with 5 slots
  .. .. .. .. ..@ type      : chr(0)
  .. .. .. .. ..@ values    : logi(0)
  .. .. .. .. ..@ color     : logi(0)
  .. .. .. .. ..@ names     : logi(0)
  .. .. .. .. ..@ colortable: logi(0)
  .. .. ..@ title   : chr(0)
  .. .. ..@ extent  :Formal class 'Extent' [package "raster"] with 4 slots
  .. .. .. .. ..@ xmin: num -9.56
  .. .. .. .. ..@ xmax: num -5.5
  .. .. .. .. ..@ ymin: num 38.9
  .. .. .. .. ..@ ymax: num 43.8
  .. .. ..@ rotated : logi FALSE
  .. .. ..@ rotation:Formal class '.Rotation' [package "raster"] with 2 slots
  .. .. .. .. ..@ geotrans: num(0)
  .. .. .. .. ..@ transfun:function ()
  .. .. ..@ ncols   : int 1945
  .. .. ..@ nrows   : int 2364
  .. .. ..@ crs     :Formal class 'CRS' [package "sp"] with 1 slot
  .. .. .. .. ..@ projargs: chr "+proj=longlat +datum=WGS84 +no_defs
+ellps=WGS84 +towgs84=0,0,0"
  .. .. ..@ history : list()
  .. .. ..@ z       : list()
  ..@ binary               :Formal class 'RasterLayer' [package
"raster"] with 12 slots
  .. .. ..@ file    :Formal class '.RasterFile' [package "raster"] with 13 slots
  .. .. .. .. ..@ name        : chr ""
  .. .. .. .. ..@ datanotation: chr "FLT4S"
  .. .. .. .. ..@ byteorder   : chr "little"
  .. .. .. .. ..@ nodatavalue : num -Inf
  .. .. .. .. ..@ NAchanged   : logi FALSE
  .. .. .. .. ..@ nbands      : int 1
  .. .. .. .. ..@ bandorder   : chr "BIL"
  .. .. .. .. ..@ offset      : int 0
  .. .. .. .. ..@ toptobottom : logi TRUE
  .. .. .. .. ..@ blockrows   : int 0
  .. .. .. .. ..@ blockcols   : int 0
  .. .. .. .. ..@ driver      : chr ""
  .. .. .. .. ..@ open        : logi FALSE
  .. .. ..@ data    :Formal class '.SingleLayerData' [package
"raster"] with 13 slots
  .. .. .. .. ..@ values    : logi(0)
  .. .. .. .. ..@ offset    : num 0
  .. .. .. .. ..@ gain      : num 1
  .. .. .. .. ..@ inmemory  : logi FALSE
  .. .. .. .. ..@ fromdisk  : logi FALSE
  .. .. .. .. ..@ isfactor  : logi FALSE
  .. .. .. .. ..@ attributes: list()
  .. .. .. .. ..@ haveminmax: logi FALSE
  .. .. .. .. ..@ min       : num Inf
  .. .. .. .. ..@ max       : num -Inf
  .. .. .. .. ..@ band      : int 1
  .. .. .. .. ..@ unit      : chr ""
  .. .. .. .. ..@ names     : chr ""
  .. .. ..@ legend  :Formal class '.RasterLegend' [package "raster"]
with 5 slots
  .. .. .. .. ..@ type      : chr(0)
  .. .. .. .. ..@ values    : logi(0)
  .. .. .. .. ..@ color     : logi(0)
  .. .. .. .. ..@ names     : logi(0)
  .. .. .. .. ..@ colortable: logi(0)
  .. .. ..@ title   : chr(0)
  .. .. ..@ extent  :Formal class 'Extent' [package "raster"] with 4 slots
  .. .. .. .. ..@ xmin: num -180
  .. .. .. .. ..@ xmax: num 180
  .. .. .. .. ..@ ymin: num -90
  .. .. .. .. ..@ ymax: num 90
  .. .. ..@ rotated : logi FALSE
  .. .. ..@ rotation:Formal class '.Rotation' [package "raster"] with 2 slots
  .. .. .. .. ..@ geotrans: num(0)
  .. .. .. .. ..@ transfun:function ()
  .. .. ..@ ncols   : int 360
  .. .. ..@ nrows   : int 180
  .. .. ..@ crs     :Formal class 'CRS' [package "sp"] with 1 slot
  .. .. .. .. ..@ projargs: chr "+proj=longlat +datum=WGS84
+ellps=WGS84 +towgs84=0,0,0"
  .. .. ..@ history : list()
  .. .. ..@ z       : list()
  ..@ evaluation           :'data.frame':	1 obs. of  7 variables:
  .. ..$ threshold    : num 0.376
  .. ..$ AUC          : num 0.808
  .. ..$ omission.rate: num 0.247
  .. ..$ sensitivity  : num 0.753
  .. ..$ specificity  : num 0.863
  .. ..$ prop.correct : num 0.825
  .. ..$ Kappa        : num 0.617
  ..@ variable.importance  :'data.frame':	1 obs. of  10 variables:
  .. ..$ PAR      : num 11.3
  .. ..$ Vel      : num 29
  .. ..$ t11MEDInv: num 10.5
  .. ..$ sal      : num 7.87
  .. ..$ t4MED    : num 10.6
  .. ..$ PIC      : num 8.89
  .. ..$ t11MINVer: num 5.33
  .. ..$ Silicat  : num 5.28
  .. ..$ t4MEDVer : num 2.23
  .. ..$ t11MED   : num 8.91
  ..@ data                 :'data.frame':	11297 obs. of  13 variables:
  .. ..$ X        : num [1:11297] -8.87 -8.87 -8.65 -8.65 -8.82 ...
  .. ..$ Y        : num [1:11297] 41.8 41.8 41 41 41.6 ...
  .. ..$ Presence : int [1:11297] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ PAR      : num [1:11297] 0.478 0.478 0.906 0.906 0.577 ...
  .. ..$ Vel      : num [1:11297] -0.332 -0.332 0.943 0.943 -0.332 ...
  .. ..$ t11MEDInv: num [1:11297] 1.82669 1.82669 0.00659 0.00659 -0.32422 ...
  .. ..$ sal      : num [1:11297] -7.07 -7.07 -6.93 -6.93 -7.07 ...
  .. ..$ t4MED    : num [1:11297] -0.291 -0.291 -0.267 -0.267 -0.464 ...
  .. ..$ PIC      : num [1:11297] 2.93 2.93 3.49 3.49 3.07 ...
  .. ..$ t11MINVer: num [1:11297] 3.451 3.451 0.321 0.321 -1.399 ...
  .. ..$ Silicat  : num [1:11297] 0.575 0.575 2.745 2.745 1.271 ...
  .. ..$ t4MEDVer : num [1:11297] -3.5 -3.5 -1.4 -1.4 -2.35 ...
  .. ..$ t11MED   : num [1:11297] -1.562 -1.562 -0.688 -0.688 -1.076 ...
  ..@ parameters           :'data.frame':	1 obs. of  11 variables:
  .. ..$ data           : chr "presence/absence data set"
  .. ..$ metric         : chr "ROC"
  .. ..$ cv             : chr "LOO"
  .. ..$ cv.param       : chr "|0.7|1"
  .. ..$ axes.metric    : chr "Pearson"
  .. ..$ kept.model     : chr "10"
  .. ..$ ensemble.metric: chr ".AUC"
  .. ..$ ensemble.thresh: chr "|0.75"
  .. ..$ weight         : chr "TRUE"
  .. ..$ algorithms     : chr ".GLM.GAM.RF.MARS.CTA.ANN.SVM.GBM"
  .. ..$ rep            : chr "10"

**Comment by sylvainschmitt** [comment]
See issue #40 for mdoel forecasting with MAXENT.

**Comment by jrenteriab** [comment]
> Following several demands we need to add the possibility of model forecasting inside the package with a different environment than the one used to build the SDM. For instance, it will allow to model the future distribution of a a species under climate change.



> Following several demands we need to add the possibility of model forecasting inside the package with a different environment than the one used to build the SDM. For instance, it will allow to model the future distribution of a a species under climate change.

Is it possible to disable the automatic projection function? 
I want to train the models using occurrences worldwide and project to an small environmental space. The automatic projection inside of the modelling function takes a lot of time to project the entirely world environmental space. I just need the train the models using the the world data (occurrences and environmental values) and project them  to a small area.
Thanks

**Comment by jrenteriab** [comment]
Is it possible to disable the automatic projection function?
I want to train the models using occurrences worldwide and project to an small environmental space. The automatic projection inside of the modelling function takes a lot of time to project the entirely world environmental space. I just need the train the models using the the world data (occurrences and environmental values) and project them to a small area.
Thanks
