### ISSUE TITLE
error while loading stack models with load_stack: AlgoEval.csv is empty

### ISSUE THREAD

**Issue by aniruddhamarathe** [sylvainschmitt/SSDM#101]
Hello,
I have a doubt about saving and loading stack models. By saving a stack model using save.stack(), the file "Stack/Tables/AlgoEval.csv" is generated with names of algorithms in rows and no other columns. This is what is very likely causing an error while loading the model with 'load_model' saying " more columns than col names.". I am wondering if I am missing any arguments to compute the relevant statistics. Could you please help me out here?

Thank you. Regards.
Aniruddha

Here is the example code: 

library(SSDM)
library(raster)
Env <- load_var(system.file('extdata',  package = 'SSDM'),
                categorical = 'SUBSTRATE', verbose = FALSE)
Occ <- load_occ(path = system.file('extdata',  package = 'SSDM'), Env,
                Xcol = 'LONGITUDE', Ycol = 'LATITUDE',
                file = 'Occurrences.csv', sep = ',', verbose = FALSE)
SSDM <- stack_modelling(c('CTA', 'SVM'), Occurrences, Env, rep = 1,
                        ensemble.thresh = 0,
                        Xcol = 'LONGITUDE', Ycol = 'LATITUDE',
                        Spcol = 'SPECIES', method = "pSSDM", verbose = FALSE)
save.stack(SSDM,name = "SSDM")

SSDM1 <- load_stack("SSDM","D:/My_Documents/OneDrive - Indian Institute of Science/My_Documents/R/tutorials/sdm")

**Comment by lukasbaumbach** [comment]
The load and save functions might be a little outdated, we definitely need to fix this in the next update! I can't say when this will be, however, so for now you may need to resort to other saving methods like `saveRDS()` (that's what I personally work with). Sorry...

**Comment by sylvainschmitt** [comment]
There is an issue with your minimal example. Using SSDM example this is working:
```
> data(Env)
> data(Occurrences)
> 
> # SSDM building
> SSDM <- stack_modelling(c('CTA', 'SVM'), Occurrences, Env, rep = 1,
+                         Xcol = 'LONGITUDE', Ycol = 'LATITUDE',
+                         Spcol = 'SPECIES')
> save.stack(SSDM, name = "test_stack")
> readr::read_csv("test_stack/Species/elliptica/Tables/AlgoEval.csv")
New names:                                                                                                                                               
• `` -> `...1`
Rows: 1 Columns: 10
── Column specification ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: ","
chr (1): ...1
dbl (9): threshold, AUC, omission.rate, sensitivity, specificity, prop.correct, Kappa, calibration, kept.model

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
# A tibble: 1 × 10
  ...1                       threshold   AUC omission.rate sensitivity specificity prop.correct Kappa calibration kept.model
  <chr>                          <dbl> <dbl>         <dbl>       <dbl>       <dbl>        <dbl> <dbl>       <dbl>      <dbl>
1 elliptica.CTA.SDM.ensemble      1.00 0.833         0.167           1       0.667        0.833 0.667       0.511          1
``
