### ISSUE TITLE
arguments imply differing number of rows

### ISSUE THREAD

**Issue by chenqh0618** [sylvainschmitt/SSDM#104]
Sorry to bother, but I tried many times and could not solved this problem.
when I modeling with following codes, I got an error:
 "Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 1, 2, 0" ,
 this happened seems in the Model evaluation part.
thanks in advance.

my code as follows,  `occur` is an data.frame with 3 cols("sp","lon","lat" ) , `env_sp` is a raster stack with 7 layers
 
```
sdm <- SSDM::modelling(
    algorithm = "MAXENT",
    Occurrences = occur,
    Env = env_sp,
    Xcol = "lon",
    Ycol = "lat",
    rep=3
  )
```

**Comment by sylvainschmitt** [comment]
Could you sent  reproducible example with package data:
```
data(Env)
data(Occurrences)
Occurrences <- subset(Occurrences, Occurrences$SPECIES =='elliptica')
sdm <- SSDM::modelling(
    algorithm = "MAXENT",
    Occurrences = Occurrences,
    Env = Env,
    Xcol ='LONGITUDE', 
    Ycol ='LATITUDE',
    rep=3
  )
```

And if this work can you send a summary of your data ?

**Comment by chenqh0618** [comment]
thank you very much!
the problem was caused by my data, in which the occurances are outside of the env raster.

I am so sorry for my carelessness, and thanks again!
