### ISSUE TITLE
Trouble loading raster's remain in new version

### ISSUE THREAD

**Issue by Caelin1234** [sylvainschmitt/SSDM#109]
Hi,
I am also experiencing trouble loading raster's in the gui.

Thanks.

**Comment by sylvainschmitt** [comment]
Hi, can you give more information. a minimal example and the version of SSDM used. Thanks, Sylvain

**Comment by Caelin1234** [comment]
I think it may have been my raster or computer. my new laptop has no issues loading raster's in gui. Thanks!
