### ISSUE TITLE
How to calculate more ensemble.metric, for example calibration error (ECE), mean calibration error (MCE) and Continuous Boyce Index (CBI)?

### ISSUE THREAD

**Issue by Otoliths** [sylvainschmitt/SSDM#111]
Hi Sylvain SCHMITT,
    How to calculate more ensemble.metric, for example calibration error (ECE), mean calibration error (MCE) and Continuous Boyce Index (CBI)?
 
for example:
> library(ENMTools)
> data(euro.worldclim)
> data(iberolacerta.clade)
> monticola.glm <- enmtools.glm(iberolacerta.clade$species$monticola, env = euro.worldclim, f = pres ~ bio1 + bio9, test.prop = 0.3)
> enmtools.calibrate(monticola.glm)

#Calibration metrics for uncalibrated model: 

|       ECE|       MCE| ECE.equal.width| MCE.equal.width| boyce.index|
|---------:|---------:|---------------:|---------------:|-----------:|
| 0.2431281| 0.0469456|       0.2431281|       0.0621923|       0.101|

#Hosmer and Lemeshow goodness of fit (GOF) test

#data:  this.pa, pred.df$prob
#X-squared = 131.28, df = 9, p-value < 2.2e-16

Thanks!

**Comment by lukasbaumbach** [comment]
Hi,

seems you confused packages... this is SSDM, not [ENMTools](https://github.com/danlwarren/ENMTools). In SSDM only the ensemble metrics AUC, Kappa, sensitivity, specificity, proportion of correctly predicted occurrences and calibration statistic (Naimi & Araujo) are implemented.
However, you could calculate your desired metrics externally in ENMTools and make a post-hoc selection for your SSDM ensemble.
Luckily for you, I have also worked with ENMTools and wrote a function to convert from an SSDM `Algorithm.SDM` to an ENMTools model.

Here's the function, `from` is the Algorithm.SDM, `suitability.map` is optional (only applies if you stored the map on disk rather than inside the `Algorithm.SDM` object). From there, it's easy to continue in ENMTools with `enm.calibrate`.   Good luck!

```
ssdm2enmtools <- function(from,suitability.map=NULL){
  modelclass <- class(from)
  algo <- sub(".SDM","",modelclass)
  sourcepkg <- attributes(modelclass)$package
  model <- SSDM:::get_model(from)
  model.formula <-"x~y" 
  species.name <- from@name
  training.data <- from@data[which(from@data$train),-which(colnames(from@data)=="train")]
  test.data <- from@data[which(!from@data$train),-which(colnames(from@data)=="train")]
  if(is.null(suitability.map)){suitability.map <- from@projection}
  
  output <- list()
  output[["species.name"]] <- species.name
  output[["formula"]] <- model.formula
  col.inds <- sapply(c("X","Y","Presence"),function(x) which(colnames(training.data)==x),simplify = FALSE)
  col.inds$Predictors <- which(!colnames(training.data)%in%c("X","Y","Presence"))
  colnames(training.data)[c(col.inds$X,col.inds$Y,col.inds$Presence)] <- c("Longitude","Latitude","presence")
  training.data.formatted <- training.data[,c(col.inds$X,col.inds$Y,col.inds$Predictors,col.inds$Presence)]
  output[["analysis.df"]] <- training.data.formatted
  test.data.formatted <- test.data[which(test.data$Presence==1),c(col.inds$X,col.inds$Y)]
  colnames(test.data.formatted) <- c("Longitude","Latitude")
  output[["test.data"]] <- test.data.formatted
  output[["test.prop"]] <- round(sum(test.data$Presence==1)/(sum(test.data$Presence==1)+sum(training.data.formatted$presence==1)),digits=1)
  output[["model"]] <- model
  trainp <- raster::extract(suitability.map,training.data.formatted[,c("Longitude","Latitude")])
  testp <- raster::extract(suitability.map,test.data.formatted[,c("Longitude","Latitude")])
  training.evaluation <- dismo::evaluate(p=trainp[which(training.data.formatted$presence==1)], a=trainp[which(training.data.formatted$presence==0)])
  test.evaluation <- dismo::evaluate(p=testp, a=raster::extract(suitability.map,training.data.formatted[which(training.data.formatted$presence==0),c("Longitude","Latitude")]))
  output[["training.evaluation"]] <- training.evaluation # dismo evaluate object training presences&all absences
  output[["test.evaluation"]] <- test.evaluation # dismo evaluate object test presences&all absences
  output[["env.training.evaluation"]] <- NULL # training presences & background points as absences
  output[["env.test.evaluation"]] <- NULL # test presences & background points as absences
  output[["rts.test"]] <- NA
  names(suitability.map) <- "layer"
  output[["suitability"]] <- suitability.map
  output[["notes"]] <- "Imported from SSDM"
  
  
  
  class(output) <- c(paste0("enmtools.",tolower(algo)), "enmtools.model")
  return(output)
}
```

**Comment by Otoliths** [comment]
@Sylvain SCHMITT, thanks a million for your help. I can’t wait to run the code you provided.

**Comment by lukasbaumbach** [comment]
It's not fully fleshed out yet (I think), but I added it to our "next update" to do list (let's see when this will happen haha).
