### ISSUE TITLE
Evaluation metrics for future projection

### ISSUE THREAD

**Issue by AJ-KBA** [sylvainschmitt/SSDM#113]
I would like to know how the SSDM function 'project' is able to return evaluation metrics such as 'AUC', 'prop.correct' when there are no occurrences (train/test) for future scenarios?

**Comment by lukasbaumbach** [comment]
The evaluation metrics refer to the original model you used for projection. The `project` function gives you the option to A) just return the projected (future scenario) raster (`output.format="rasters"`) or B) return the original model with exchanged raster in the `@projection` slot (`output.format="model"`) Also see the documentation for `project`.

**Comment by AJ-KBA** [comment]
> The evaluation metrics refer to the original model you used for projection. The `project` function gives you the option to A) just return the projected (future scenario) raster (`output.format="rasters"`) or B) return the original model with exchanged raster in the `@projection` slot (`output.format="model"`) Also see the documentation for `project`.

Thank You. This was helpful.
