### ISSUE TITLE
All the exported data is training data, Can you also export test data?

### ISSUE THREAD

**Issue by Otoliths** [sylvainschmitt/SSDM#114]
@sylvainschmitt,

All the exported data is training data, Can you also export test data?

for example
Not run: 
###### Loading data
```
data(Env)
data(Occurrences)
Occurrences <- subset(Occurrences, Occurrences$SPECIES == 'elliptica')
```

###### ensemble SDM building
```
ESDM <- ensemble_modelling(c('CTA', 'MARS'), Occurrences, Env, rep = 1,
                          Xcol = 'LONGITUDE', Ycol = 'LATITUDE',
                          ensemble.thresh = c(0.6))
table(ESDM@data$train)
```
```
TRUE 
1011 
```

I guess line 109 is wrong in the evaluate.r,
"eval.testdata <- eval.testdata[-which(names(data) == "train")] " was modified to "eval.testdata <- eval.testdata[,-which(names(data) == "train")]"

I try to fix "evalobj@data <- eval.traindata" in line 113, but it still report an error.

I also tried to add a line of code after line 125 to calculate the **Continuous Boyce Index** (CBI) of an evaluation model performance, I wonder if it is correct?

```
continuous.boyce <- ecospat::ecospat.boyce(predicted.values, eval.testdata$Presence, PEplot = FALSE)

evaldf <- data.frame(threshold=threshval, AUC=roweval@auc, omission.rate=roweval@MCR, sensitivity=roweval@TPR, specificity=roweval@TNR, prop.correct=roweval@CCR, Kappa=roweval@kappa, calibration=caleval@statistic,CBI=continuous.boyce$Spearman.cor)
```

Hirzel, A.H., G. Le Lay, V. Helfer, C. Randin and A. Guisan. 2006. Evaluating the ability of habitat suitability models to predict species presences. **_Ecol. Model_**., 199, 142-152.

looking forward to your reply!

Thanks

liuyong ding

**Comment by Otoliths** [comment]
@lukasbaumbach thank you very much!

**Comment by sylvainschmitt** [comment]
@Otoliths , the train column is giving the wrong impression. In the end all the data are used for the final fit so the whole column is set to TRUE : https://github.com/sylvainschmitt/SSDM/blob/fa784cbe1630767f544ef1883bd6f0af5606724b/R/evaluate.R#L243-L245 . But in the end all occurrences are kept:

```
> nrow(ESDM@data[ESDM@data$Presence == 1,])
[1] 11
> nrow(Occurrences)
[1] 11
``
