### ISSUE TITLE
Ensemble.SDM algorithms correlation has not been computed. 

### ISSUE THREAD

**Issue by Callahan475** [sylvainschmitt/SSDM#117]
When I am trying to stack my EDSMs, I am getting the error:
**Ensemble.SDM algorithms correlation has not been computed.** 

Running it, on a supercomputer due to size of data, when doing  SSDM_all <- Reduce("stacking", output) I get this output:

Stack creation... 
   naming... done. 
   range restriction... done. 
   diversity mapping...
 Local species richness computed by summing individual probabilities. 
 done. 
   uncertainty mapping...No uncertainty map to do uncertainty mapping done. 
   endemism mapping... done. 
   comparing variable importance... done. 
   comparing algorithms correlation...
 ARCTIC SKUA.Ensemble.SDM algorithms correlation has not been computed. 

 ARCTIC TERN.Ensemble.SDM algorithms correlation has not been computed. 
 done. 
   comparing algorithms evaluation done. 
   evaluating..

**Comment by lukasbaumbach** [comment]
Hi,

this is not an error, but just a normal progress message. It is printed, when the `@algorithm.correlation` slot in the SSDM object is empty. This again may be the case, if uncertainty computation is deactivated, which seems to apply for your case.
