### ISSUE TITLE
Response curves?

### ISSUE THREAD

**Issue by Migu95** [sylvainschmitt/SSDM#119]
Dear all,

I'm a new user of the SSDM package and I was wondering if it is possible to generate response curves from an ensemble model or from separated SDMs.

Thanks!

**Comment by sylvainschmitt** [comment]
Dear Miguel,

Unfortunately this was not planned in `SSDM` original development and this is a feature we should add in the future developments. 

However, response curve are just predictions of base model in SSDM so you can hack the code similarly to #10 and access the predict internal function. 

Sorry this is the only suggestion I can give you yet. Or if you have time you can try implementing it.

Best,

*Sylvain*
