### ISSUE TITLE
Please remove dependencies on **rgdal**, **rgeos**, and/or **maptools**

### ISSUE THREAD

**Issue by rsbivand** [sylvainschmitt/SSDM#123]
This package depends on (depends, imports or suggests) **raster** and one or more of the retiring packages **rgdal**, **rgeos** or **maptools** (https://r-spatial.org/r/2022/04/12/evolution.html, https://r-spatial.org/r/2022/12/14/evolution2.html). Since **raster** `3.6.3`, all use of external FOSS library functionality has been transferred to **terra**, making the retiring packages very likely redundant. It would help greatly if you could remove dependencies on the retiring packages as soon as possible.

**Comment by sylvainschmitt** [comment]
rgdal and sp were removed in https://github.com/sylvainschmitt/SSDM/commit/e03e8826b820f636bec032bb3a3553546787cf67 . raster is still to be removed.

**Comment by AMBarbosa** [comment]
Hi, any plans to implement `terra` `SpatRaster` inputs soon, e.g. in the `Env` argument of `ensemble_modelling()`? Cheers
