### ISSUE TITLE
pAUC? 

### ISSUE THREAD

**Issue by KateOverly-NOAA** [sylvainschmitt/SSDM#125]
Hello there, 

Is there a way to implement a partial AUC (pAUC) in the SSDM package? In Peterson et al. (2008) they discuss that pAUC is a better way to leave the evaluation of absences and concentrate only on the evaluation of presences in a presence-only model, with their reasoning being that the AUC, Kappa, and TSS require true absence (which for mobile marine animals is tricky - in my case). Wondering if there is a way to evaluate the model performance under a pAUC scheme instead? 

Thank you!

Best, 
Kate

**Comment by sylvainschmitt** [comment]
Sorry but we do not have a lot of mean to maintain the package yet, so no further enhancement are scheduled. If you wish to help this is an open source package and you could suggest pull requests. However if not I won't include this yet, and I'll thus close your issue. Don't hesitate to reopen it if you want to work on it and you want some guidance.
