### ISSUE TITLE
More explicit error when doing ensemble modelling

### ISSUE THREAD

**Issue by Rekyt** [sylvainschmitt/SSDM#22]
Hi @sylvainschmitt,

I was using the function `stack_modelling()` with simulated data and had issues with ensemble modelling for each species, because the AUC threshold was too high for the models I had.
I had this error:
https://github.com/sylvainschmitt/SSDM/blob/51df69e1aa86c42a33e645b5c8a33bdcda76f24a/R/stack_modelling.R#L434
It took me a certain time to understand which threshold parameter I should use between `thresh` and `ensemble.thresh`.

The error could be made more explicit such as:
"Less than two species models were retained, you should lower the ensemble threshold value"
or
"Less than two species models were retained, you should lower `ensemble.thresh`"
or
"Less than two species models were retained, you should lower the threshold value to select ensemble models"

**Comment by sylvainschmitt** [comment]
You are totally right ! I pick one or a mix of your proposition next week because I am a bit overload this week.
