### ISSUE TITLE
species data table preparation

### ISSUE THREAD

**Issue by BoiMau** [sylvainschmitt/SSDM#23]
hi all
i'm new to ecological modeling and R, i have recently built my models in BIOMODv2, i'm keen in using SSDM for computing species richness and endemism mapping. i realise one cannot use ensemble models fitted in BIOMOD to build SSDM. i now have to re build the models using the package SSDM, my issue is i have a presence,absence species dataset, with 162 species across 194 locations (sample below). i reckon i'll have to have 4 variables/ Columns with headings, species,lon,lat, presence, but i wonder how i can prepare the dataset table in such a way that i don't end up with lots an lots of rows.

![sample](https://user-images.githubusercontent.com/20436377/38176792-3f045c44-35ed-11e8-8e50-215c56b8bc82.PNG)

Thank you in advance and looking forward to your responses
BoiChaza

**Comment by sylvainschmitt** [comment]
You'll effectively end up with a lots and lots of rows but that's not really an issue. It is the difference between so called wide and long table formats. There is a nice explanation with R package `reshape2` http://seananderson.ca/2013/10/19/reshape/ . Consequently using reshape2 you can format your table with only on command:
```
data_long <- melt(data_wide, id.vars = c("X", "Y"), variable.name = "species", value.name = "presence")
```

**Comment by BoiMau** [comment]
Dear Sylvain
Thank you very much for the prompt response, this has worked.
I’m now working on a code to run the SSDM.

Thank you once again
Boi

**Comment by BoiMau** [comment]
Dear Sylvain
I was wondering if you could help, I’m using the below code to compute SSDM in a linux cluster, I however get an error message as below. Investigation into the error doesn’t source me any useful solutions. Have you come across the error?

Error in checkForRemoteErrors(val) :
  20 nodes produced errors; first error: comparison of these types is not implemented

###CODE I USE##
Env <- load_var(path = getwd(), files = NULL, format = c(".asc"), categorical = NULL,
                Norm = TRUE, tmp = TRUE, verbose = TRUE, GUI = FALSE)

Occurrences <- load_occ(path = getwd(), Env, file = "SppData1Occ.csv",
                        Xcol = "longitude", Ycol = "latitude", Spcol = "species", GeoRes = TRUE,
                        sep = ",", verbose = TRUE, GUI = FALSE)
head(Occurrences)
warnings()
SSDM <- stack_modelling(c("GBM", "RF", "MAXENT"), Occurrences, Env, Xcol = "longitude",
                        Ycol = "latitude", Pcol = "presence", Spcol = "species", rep = 1,
                        name = "Stack", save = TRUE, path = getwd(), PA =NULL,
                        cv = "k-fold", cv.param = c(10,1), thresh = 1001,
                        axes.metric = "Pearson", uncertainty = TRUE, tmp = TRUE,
                        ensemble.metric = c("AUC"), ensemble.thresh = c(0.5), weight = FALSE,
                        method = "PRR.MEM", metric = "SES", range = NULL,
                        endemism = c("CWEI", "Binary"), verbose = TRUE, GUI = FALSE,cores = 20)

save.stack(SSDM, name = "150s_Present", path = getwd(),
           verbose = TRUE, GUI = FALSE)



###ERROR MESSAGE I GET###
Exporting environment to clusters
Error in checkForRemoteErrors(val) :
  20 nodes produced errors; first error: comparison of these types is not implemented
In addition: Warning messages:
1: In .Internal(gc(verbose, reset)) :
  closing unused connection 7 (<-localhost:11836)
2: In .Internal(gc(verbose, reset)) :
  closing unused connection 6 (<-localhost:11836)
3: In .Internal(gc(verbose, reset)) :
  closing unused connection 5 (<-localhost:11836)
4: In .Internal(gc(verbose, reset)) :
  closing unused connection 4 (<-localhost:11836)
5: In .Internal(gc(verbose, reset)) :
  closing unused connection 3 (<-localhost:11836)
6: In dir.create(paste0(tmppath, "/.enms")) :
  '/tmp/Rtmpy7pdZs/NumberOne/.enms' already exists
>

Thanks and looking forward to hearing from you
Boi

**Comment by sylvainschmitt** [comment]
Have you tried without the cluster on few species ?

**Comment by BoiMau** [comment]
Dear Sylvain
Thank you for the response.
I have tried the code on a subset of species, what I did was create a presence occurrence subset of species with 3 variables, Species,longitude,latitude , the code seems to have run okay until to the stacking stage, it stopped and gave the below error. It says the environment data set is not a raster or a raster stack, but this is the same env data set used to create the ensemble models. I wonder why it gives an error when it comes to building the stack. Please see below. Again I wonder why the code works with a subset of species occurrence table and not with presence/absence table.

#### Ensemble models creation #####

Opening clusters, 1 cores
Exporting environment to clusters
Closing clusters
#### Species stacking with ensemble models #####

Stack creation...
   naming... done.
   range restriction... done.
   diversity mapping...
Local species richness computed by probability ranking from MEM.
Error in modelling(algorithms[i], Occurrences, Env, Xcol = Xcol, Ycol = Ycol,  :
  Environment data set is not a raster or a raster stack
In addition: Warning messages:
1: In dir.create(paste0(tmppath, "/.enms")) :
  'C:\Users\LINA25~1.009\AppData\Local\Temp\RtmpieP218\NumberOne\.enms' already exists
2: In if (is.null(value)) { :
  closing unused connection 3 (<-ouce38-103.ouce.ox.ac.uk:11271)
Error in modelling(algorithms[i], Occurrences, Env, Xcol = Xcol, Ycol = Ycol,  :
  Environment data set is not a raster or a raster stack
Error in modelling(algorithms[i], Occurrences, Env, Xcol = Xcol, Ycol = Ycol,  :
  Environment data set is not a raster or a raster stack
Error in (function (classes, fdef, mtable)  :
  unable to find an inherited method for function ‘ensemble’ for signature ‘"missing"’

thank you and look forward to hearing from you
Boi

**Comment by sylvainschmitt** [comment]
Use preferentially issue #24 because this one is closed
