### ISSUE TITLE
Error in checkForRemoteErrors(val) :   one node produced an error: comparison of these types is not implemented >

### ISSUE THREAD

**Issue by BoiMau** [sylvainschmitt/SSDM#25]
Dear Sylvain 
i have spent some time trying to resolve this error with no success. it seems the error has something to do with the way the SSDM software does the parallel computing, its more of an internally produced error within the package. Regardless of which platform i run the code on, whether the linux cluster or my local machine i still get the same error. whether i set the cores to 1 0r 10, the error message is produced.
could you please assist with this?
#### Ensemble models creation #####

Opening clusters, 1 cores
starting worker pid=58959 on localhost:11123 at 14:14:11.938
Exporting environment to clusters
Error in checkForRemoteErrors(val) :
  one node produced an error: comparison of these types is not implemented
>
thanks and looking forward to hearing from you.
Boi

**Comment by sylvainschmitt** [comment]
Do not duplicate issues ! And sorry but maintaining SSDM is not part of my job currently, I am happy to do it, but it's an open and free software and I don't have that much time to do it. So I will try to continue to help you in the issue #24 but do not spam.
