### ISSUE TITLE
Error during load_stack

### ISSUE THREAD

**Issue by rishisingh1992** [sylvainschmitt/SSDM#29]
Dear Sylvian,

I used stack_modelling function to estimate the certain species in India. After the code ran completely, I plotted it to check for the results which looked fine to me. I saved the model and closed R. Now, when I try to load the model using load_stack command it throws me an error which is as follows:

> load_stack(name="Stack_maxglm", path=getwd(),GUI=FALSE)
Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  more columns than column names

So it is reading the files in the 'Tables' folder but I cannot seem to get around this. Your help would be greatly appreciated. 

Regards
Rishi

**Comment by sylvainschmitt** [comment]
Are you sure of your stack path and name ? It should be the same you used with save function. Have you tried to open it with the GUI ?

Could you trace back the error to know exactly which table has thrown the bug ?

Best,

Sylvain
