### ISSUE TITLE
PA: strat = "2nd" instead of "disk"

### ISSUE THREAD

**Issue by ejosymart** [sylvainschmitt/SSDM#36]
Dear Sylvain

When I write in the PA argument strat = "disk", the message is:

Pseudo absence selection... 
   random selection 
   done. 

I compared the results using random and disk strategies, they are different, but the message (verbose = TRUE) is always 'random selection done'.

**Comment by sylvainschmitt** [comment]
Sorry apparently `PA` disk argument has been misnamed `2nd`
https://github.com/sylvainschmitt/SSDM/blob/04e4c962c23e1bf5e9b782eed3b9d7d84bf7430e/R/PA.select.R#L18

**Comment by sylvainschmitt** [comment]
It"s fixed on GitHub and soon on CRAN

**Comment by sylvainschmitt** [comment]
On its way to CRAN.
