### ISSUE TITLE
Multicollinearity of variables

### ISSUE THREAD

**Issue by magdaresende** [sylvainschmitt/SSDM#37]
Dear Sylvain, 
Is there a way to check multicollinearity between the environmental variables?

Thanks in advance,
Magda

**Comment by sylvainschmitt** [comment]
Dear Magda,

Multi-collinearity between environmental variables has not been implemented within the `SSDM` package itself but can be easily done thanks to the `raster` package:
```
layerStats(raster_stack, 'pearson', na.rm=T)
```
And it's exactly what we've done in the first example of the article corresponding to the package: https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.12841

Best,

Sylvain
