### ISSUE TITLE
Environmental conditions with different cell size

### ISSUE THREAD

**Issue by magdaresende** [sylvainschmitt/SSDM#38]
Dear Sylvain,

Thank you for the last reply.

It is possible to calculate an SDM using multiple environmental conditions with different cell sizes?

Thanks in advance,
Magda

**Comment by magdaresende** [comment]
I am trying to calculate an SDM with six environmental variables. Three of them have a cell size of 0.250 and the others have a cell size of 0.0027. 
I am using a presence only dataset and I get stuck on the Pseudo absence selection step (output below). 

Is there a way to fix this? Or I can't calculate an SDM with different cell sizes?


Thanks in advance,
Magda


Variables loading 
Variables treatment 
   resolution and extent adaptation...
 osat is aggregated to the coarsest resolution 

 salin is aggregated to the coarsest resolution 

 b_temp_kelvin is aggregated to the coarsest resolution 
   done... 
class       : RasterStack 
dimensions  : 44, 56, 2464, 6  (nrow, ncol, ncell, nlayers)
resolution  : 0.2511, 0.2511  (x, y)
extent      : -34.99974, -20.93814, 32.95137, 43.99977  (xmin, xmax, ymin, ymax)
coord. ref. : NA 
names       :        osat,       salin, b_temp_kelvin,        bath,       Slope,      Aspect 
min values  :    72.07211,    34.88971,     275.65901,   390.02590,   -68.28064,  -413.73165 
max values  :   85.064929,   35.724814,    279.288254, 4471.050823,    4.795267,  100.533374 

Occurrences loading 
1 geographical resampling 
              SPECIES LONGITUDE LATITUDE
1  Beryx decadactylus   -25.125   36.875
2  Beryx decadactylus   -24.875   36.875
3  Beryx decadactylus   -25.875   37.125
4  Beryx decadactylus   -25.625   37.125
5  Beryx decadactylus   -25.125   37.125
6  Beryx decadactylus   -30.875   37.375
Data check ... 
No presence column, presence-only data set is supposed.
Pseudo-absence selection will be computed.
   done. 

Pseudo absence selection... 
   random selection

**Comment by sylvainschmitt** [comment]
As described in the article you have to upscale or downscale rasters to homogenize their resolution.
