### ISSUE TITLE
Response curves

### ISSUE THREAD

**Issue by magdaresende** [sylvainschmitt/SSDM#39]
Dear Sylvain,
Is there a way to see the response curves (describing how the species’ occurrence depends on the climate variables)?

Thanks in advance,
Magda

**Comment by sylvainschmitt** [comment]
Dear Magda,

Unfortunately response curves have not been included in the original architecture of the SSDM package. The only possible way I see for for the moment is to use the internal `SSDM:::get_model` function (https://github.com/sylvainschmitt/SSDM/blob/master/R/get_model.R) and to then use the `predict` method on the output with set environmental values to build the response curve as in the `project` method (https://github.com/sylvainschmitt/SSDM/blob/master/R/project.R). But I'll think to add this functionality in further development of the SSDM package.

Best,
Sylvain

**Comment by CarvalhoResearch** [comment]
I'm trying to see my response curves for the environmental variables, to check the linear relationship that @lukasbaumbach mentioned in issue # 97. 
I got it using: names(response(SSDM:::get_model(RF))) for GAM and GLM, but for RF I get this error:

Warning message in randomForest.default(m, y, ...):
“The response has five or fewer unique values.  Are you sure you want to do regression?”
Error in .local(x, ...): The model object does not seem to have the data used to fit it. Provide these with a "data= " argument
Traceback:

1. response(SSDM:::get_model(RF))
2. response(SSDM:::get_model(RF))
3. .local(x, ...)
4. stop("The model object does not seem to have the data used to fit it. Provide these with a \"data= \" argument")

Thank you!
