### ISSUE TITLE
project_internal with MAXENT

### ISSUE THREAD

**Issue by msundara101** [sylvainschmitt/SSDM#40]
Hi Sylvain,

I am hoping to use your R package and 'project_internal' for my dataset, I was able to reproduce the example you have here for a GLM model. I noticed that when the modelling algorithm is MAXENT, project_internal reproduces the original raster file. Is there a way to project occurrence in a new environmental space for a MAXENT model?

Thanks,
Mekala

**Comment by sylvainschmitt** [comment]
Unfortunately as explained here https://github.com/sylvainschmitt/SSDM/issues/10#issuecomment-398876394 is is currently not possible with MAXENT. But the project function for MAXENT could be easily written back locally to include two environmental stacks and thus be used to make projection in a new environmental space:
https://github.com/sylvainschmitt/SSDM/blob/8cc42286b7a8fc081c3450ac44c80f878a0d6661/R/project.R#L36-L59
to:
```
project <- function(obj, Env0, Env) {
  model = SSDM:::get_model(obj, Env0)
  proj = raster::predict(Env, model, fun = function(model, x) {
    x = as.data.frame(x)
    for (i in seq_len(length(Env@layers))) {
      if (Env[[i]]@data@isfactor) {
        x[, i] = as.factor(x[, i])
        x[, i] = droplevels(x[, i])
        levels(x[, i]) = Env[[i]]@data@attributes[[1]]$ID
      }
    }
    return(predict(model, x))
  })
  # Rescaling projection
  proj = reclassify(proj, c(-Inf, 0, 0))
  proj = proj / proj@data@max
  names(proj) = "Projection"
  obj@projection = proj
  obj@binary <- reclassify(proj, c(-Inf,obj@evaluation$threshold,0,
                                    obj@evaluation$threshold,Inf,1))
  return(obj)
})
```

**Comment by msundara101** [comment]
Hi Sylvain,

Thanks for the message. Would this provide the same result as switching tmp to FALSE?

Regards,
Mekala
