### ISSUE TITLE
"Error factors[[j]]: subscript out of bounds" if all environmental layers are numeric

### ISSUE THREAD

**Issue by lukasbaumbach** [sylvainschmitt/SSDM#49]
It seems that when all environmental layers are numeric, the supplied factor argument to the `raster::predict` function is an empty list. Predict then looks into the first element of the factor list and fails, because there is none. Setting `if(length(factors)==0) factors <- NULL` would probably resolve this issue.

**Comment by sylvainschmitt** [comment]
Ok that's problematic as it has been published in the last version of CRAN to answer `raster` package changes and it means that the version as a major bug into it. Could you implement and test your fix and finally Pull Request it ? If it's working I'll submit it quickly to CRAN avoid to much users to have the bug.

**Comment by sylvainschmitt** [comment]
In fact I'll take care of it.

**Comment by sylvainschmitt** [comment]
It"s fixed on GitHub and soon on CRAN

**Comment by keefer56** [comment]
For my masters project I am trying to use SSDM/eSDM. I am using rasters for the 19 bioclimatic variables and another for elevation.

When running the SSDM we keep getting the error "Error in factors[[j]] : subscript out of bounds”.

My code is

Keith_birds_all <- stack_modelling(c('GLM','GBM','ANN'), Keith_birds, Env1, Xcol = 'Longtitude', Ycol = 'Latitude', Spcol='SpeciesID', rep=5, 
                                   path=getwd(), cv = "holdout", cv.param = c(0.7, 1), thresh = 1001,
                                   axes.metric = "Pearson", uncertainty = TRUE, tmp = FALSE,
                                   ensemble.metric = c("AUC"), ensemble.thresh = c(0.7), weight = TRUE,
                                   method = "pSSDM", metric = "SES", rep.B = 1000, range = NULL,
                                   endemism = c("WEI", "Binary"), verbose = TRUE, GUI = FALSE, cores = 2)


My data are attached.

When running the eSDM we get a fatal error (code as follows) : -

eSDM <- ensemble_modelling(c('GLM','GBM','ANN'), Keith_birds, Env, Xcol = 'Longtitude', Ycol = 'Latitude', Spcol='SpeciesID', rep=5, 
                           path=getwd(), cv = "holdout", cv.param = c(0.7, 1), thresh = 1001,
                           axes.metric = "Pearson", uncertainty = TRUE, tmp = FALSE,
                           ensemble.metric = c("AUC"), ensemble.thresh = c(0.7), weight = TRUE,
                           method = "pSSDM", metric = "SES", rep.B = 1000, range = NULL,
                           endemism = c("WEI", "Binary"), verbose = TRUE, GUI = FALSE, cores = 2)

I would appreciate any assistance you can provide on this.

**Comment by keefer56** [comment]
I see the fix is being organised- thanks for the rapid response.

**Comment by sylvainschmitt** [comment]
In waiting for the new CRAN version install GitHub version of SSDM:
```
devtools::install_github("sylvainschmitt/SSDM")
```

**Comment by sylvainschmitt** [comment]
On its way to CRAN.
