### ISSUE TITLE
More presences in slot @data that original presences

### ISSUE THREAD

**Issue by VirginiaMorera** [sylvainschmitt/SSDM#50]
Hello, 

Could someone clarify what's stored in the slot `@data` of an `Ensemble.ESDM` object? 

I've tried with several presence-only datasets containing around 2,000 presences, and the slot data contains, for all of them, between 50,000 and 70,000 absences (I assume they are the calculated pseudoabsences) and between 15,000 and 62,000 presences (this is what puzzles me, where do these extra-presences come from?)

Haven't found any clarification in the manual or the paper on this subject! 

Thanks!

**Comment by sylvainschmitt** [comment]
Hello, I suppose that you have between 7.5 and 31 single SDM behind your ESDM ? The `ESDM@data` is not really useful, it's simply the binding of all single SDMs data:
https://github.com/sylvainschmitt/SSDM/blob/48c4648eb4786bfae98b3e7a77259ca0581e6c9b/R/ensemble.R#L166-L172
It might be replaced by something more useful in future implementations of the package.

**Comment by VirginiaMorera** [comment]
You're right, it's a replica of "data" for each model it runs, I suppose! I tested this by removing duplicates and it went back to my original number of points. I guess this can be a useful slot, that allows you to have all data and results in the same object, making post-processing tidyer! At least, I am finding it useful. Not essential, but useful! 

Thanks for the quick reply!
