### ISSUE TITLE
Problem with loading rasters

### ISSUE THREAD

**Issue by SergeiVolis** [sylvainschmitt/SSDM#52]
Dear Sylvain,

I am trying to use your program SSDM through gui, but I can not even pass the first stage of data loading. I AM USING YOUR EXAMPLE DATA. However, after selecting your 3 environmental variables (RAINFALL, SUBSTRATE, TEMPERATURE) and clicking "load" I get a message "Environmental variables loading failed, please check your inputs and try again". The R console gives the following message:

Listening on http://127.0.0.1:4983
Warning in force(expr) :
?? strings not representable in native encoding will be translated to UTF-8
Error in .checkargs(path = path, files = files, format = format, categorical = categorical,?? :
?? format parameter should be .grd, .tif, .asc, .sdat, .rst, .nc, .tif, .envi, .bil or .img

Please, explain where is the problem. 

In your E-mail to me you wrote that the problem is in data format, but the three files were created by you and included in "exdata" folder. I did not change them.

Sergei

**Comment by sylvainschmitt** [comment]
Which version of SSDM did you used ? It's working perfectly fine on SSDM CRAN v0.2.6 on my personal computer:
![image](https://user-images.githubusercontent.com/16331085/59587269-31449700-90e5-11e9-86c6-58a03e85fbf2.png)
![image](https://user-images.githubusercontent.com/16331085/59587298-3f92b300-90e5-11e9-8518-bad36c224d62.png)

**Comment by SergeiVolis** [comment]
I just downloaded it yesterday from Github following instructions at https://www.rdocumentation.org/packages/SSDM/versions/0.2.4

**Comment by SergeiVolis** [comment]
Should I install v0.2.6 ?

**Comment by sylvainschmitt** [comment]
Give it a try, simply: install.packages("SSDM") in R.

**Comment by lukasbaumbach** [comment]
I am also experiencing the same problems. The example data works fine, but even if I try to load the very same example data from another folder I get the error message. I suspect there's a bug with the file path (maybe the extension gets could or is not retrieved correctly?).

**Comment by guilherme-atencio** [comment]
For me, not even the example data is working. 
I tried all formats, from different sources, and the error is always the same. 
A few months ago the same data worked, but something changed and now I keep getting the same error: 

Error in .checkargs(path = path, files = files, format = format, categorical = categorical,  : 
  format parameter should be .grd, .tif, .asc, .sdat, .rst, .nc, .tif, .envi, .bil or .img


I am new to GitHub, so sorry if I am doing something wrong and thanks in advance.

**Comment by robbiestill** [comment]
hi Sylvain, i'm having the same issue unfortunately - if i run load_vars() and manually input the format it works, but it won't run through the GUI 
![image](https://user-images.githubusercontent.com/57251392/68012364-bb9b2b00-fc81-11e9-9bf2-fe0be7ff456c.png)

![image](https://user-images.githubusercontent.com/57251392/68012443-f604c800-fc81-11e9-9e03-5ce8c0c00c83.png)

I installed the package yesterday and have tried both github and CRAN versions, both have the sam issue.

**Comment by lukasbaumbach** [comment]
@sylvainschmitt I think this is fixed in the forecasting branch. Didn't we merge with the master yet?

**Comment by sylvainschmitt** [comment]
It seems that we still never merged the forecasting branch to the master:
![image](https://user-images.githubusercontent.com/16331085/68132206-0ffe0f00-fefd-11e9-81d3-a036e9e5ae27.png)
Can you check that everything is good in the branch and will merge the two ? You can do it or I can deal with it, as you wish. And we should think to prepare a new version for CRAN to avoid users to have the issue when using `install.packages` in R.

**Comment by sylvainschmitt** [comment]
@robbiestill can you try to install `SSDM` from the `Forecasting-#42` branch with following code `devtools::install_github("sylvainschmitt/SSDM", ref = "Forecasting-#42")` and tell us if it fix the bug for you ?

**Comment by guilherme-atencio** [comment]
> @robbiestill can you try to install `SSDM` from the `Forecasting-#42` branch with following code `devtools::install_github("sylvainschmitt/SSDM", ref = "Forecasting-#42")` and tell us if it fix the bug for you ?

I was having the same issues loading rasters in the GUI and doing the install from Forecasting-#42 branch as you specified fixed the issue for me.

**Comment by sylvainschmitt** [comment]
Thank you @guilherme-atencio , we will merge Forecasting-#42 and submit a new version to CRAN to avoid this bug for future users.

**Comment by guilherme-atencio** [comment]
You're welcome!
And thank you for looking into the issue.

**Comment by robbiestill** [comment]
@sylvainschmitt sorry im having some issues installing the new version, im doing the work on an office laptop can make it difficult to reinstall non-CRAN packages  - would you mind letting me know when you've submitted the new version to CRAN? i'll definitely be able to reinstall from there!

**Comment by merel5541** [comment]
Hi! I had the same problem with the raster inputs so I tried running the code: 
`devtools::install_github("sylvainschmitt/SSDM", ref = "Forecasting-#42")`

and it gives me the following error:
`Skipping 1 packages not available: poibin
Installing 5 packages: poibin, R.utils, spam, plotrix, cli
Installing packages into ‘C:/Users/merel/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
Error: Failed to install 'SSDM' from GitHub:
  (converted from warning) package ‘poibin’ is not available (for R version 3.6.2)`

Can I ignore this error or do I need to install a different version of R?

**Comment by lukasbaumbach** [comment]
@merel5541 as far as I remember `poibin` is needed for running the 'MaximumLikelihood' method of `stack_modelling`. We might make the `poibin` package optional in future updates if it's not supported in newer R versions. I know for sure, that `SSDM` can be installed in R version 3.5.2, so in the mean time, you can try using that. If the problem persists please open a new issue, since this doesn't concern the topic of this issue.

**Comment by lukasbaumbach** [comment]
closed, very likely fixed in new version

**Comment by guilherme-atencio** [comment]
It's 2024 and I see the issue persists.
