### ISSUE TITLE
More arguments for modelling algorithms

### ISSUE THREAD

**Issue by lukasbaumbach** [sylvainschmitt/SSDM#66]
Following the discussion in #65 

> > 
> In fact we could add some `MaxEnt` options through the `...` argument capture in the `modelling` and `get_model` function:

I'm just wondering: Why not take it one step further and open this possibility for all algorithms? 
It may generally be advisable to have a list of settings for each algorithm in use, since a confusion of arguments between algorithms is possible. An example: When doing `ensemble_modelling(c('ANN','GLM', 'GAM'), Occurrences, Env, rep = 1, Xcol = 'LONGITUDE', Ycol = 'LATITUDE', epsilon=0.1, maxit=200)`
the argument `epsilon` exists in both GLM and GAM and and `maxit` exists for ANN, GLM and GAM. Recycling the argument for each algorithm is hardly desirable.
Besides, using default settings for most models is not recommended, because they are not easily generalizable.

Instead, it could be a possibility to let the user specify advanced settings (as in the original functions) by supplying a list of named vectors, e.g.: `modargs=list(glm=c(epsilon=0.1, maxit=200),ann=c(maxit=200))`.  

@sylvainschmitt What do you think?

**Comment by sylvainschmitt** [comment]
> Why not take it one step further and open this possibility for all algorithms?

It's partly done ! If you look at `modelling` function description you'll read:

> ... additional parameters for the algorithm modelling function (see details below).

The thing is that we only opened few parameters (have a look to the help). And there is effectively issues with name confusion. And I can't recall why we only opened few of them. Anyway, we could rename and open all parameters, but I wouldn't follow your strategy. Instead I'll name arguments something like `glm.epsilon` and `gam.epsilon` that would be captured by the `...` of the `modelling` functions and then used by the `get_model` function of every algorithm (similarly to what is already done).

**Comment by lukasbaumbach** [comment]
Hmm... I do not really see the advantage of renaming the arguments with their respective algorithm prefixes. Isn't it much easier to just have a list or vector of arguments to supply to each algorithm as is? If we use your suggested `algorithm.argument` format, this could be a very long line of arguments (for the `glm` function alone there are more than 17 arguments you could specify additionally to the ones that are already implemented in SSDM). Furthermore, I can't imagine yet how many of these arguments could be passed on efficiently from the `get_model` to the original algorithm functions.

Can you maybe explain your suggestion a little more?

Another way to supply the arguments could be through character vectors which can then be easily converted into arguments with `eval(parse(text=args))`. It could look like this: `ensemble_modelling(c('GLM','GAM'),Occurrences, Env, glm.args=c("epsilon=0.1","maxit=200"),gam.args=c("epsilon=0.5","maxit=100"))`.  The only thing I could not figure out about this yet, is how to leave the possibility to either keep your default settings (e.g. `maxit=500` for `GLM.SDM`) and add more arguments to them or replace the defaults and possibly add more arguments. Maybe you have an idea?

**Comment by sylvainschmitt** [comment]
> Another way to supply the arguments could be through character vectors which can then be easily converted into arguments with eval(parse(text=args)). It could look like this: ensemble_modelling(c('GLM','GAM'),Occurrences, Env, glm.args=c("epsilon=0.1","maxit=200"),gam.args=c("epsilon=0.5","maxit=100"))

Yes this is a good idea. 

> The only thing I could not figure out about this yet, is how to leave the possibility to either keep your default settings (e.g. maxit=500 for GLM.SDM) and add more arguments to them or replace the defaults and possibly add more arguments. Maybe you have an idea?

You may stock `eval(parse(text=args))` in a list or something similar before giving them to the aglorithm, and maybe you can do something like `if(is.null(obj$maxit)) maxit = 500`.

**Comment by lukasbaumbach** [comment]
Here's the current plan: 
1) set a default list argument `algo.args` for each algorithm (e.g. for GAM `gam.args=list(test="AIC",control=gam.control(epsilon=1e-08,maxit=500))`.
2) add defaults to this list, if not given (e.g. `gam.args$formula <- formula(formula)`)
3) pass the whole list as arguments to `do.call(gam,args=gam.args)`).

Advantage: handy and flexible format, easy argument checking
Disadvantage: for the example of GAM, the call is also saved in the `gam.model$call` slot, making the resulting model twice as large (mainly because of the stored training data).

I tried finding a solution via `eval(parse(text=args))` but couldn't get it to work. Especially, if the arguments were not supplied as character strings (e.g. like `list(test="'AIC'",control="gam.control(epsilon=1e-08,maxit=500)")`  - which can be uncomfortable anyways, if the argument already IS a character.

For a lack of alternatives, I'd go with the `do.call` approach and empty the `$call` slot for GAM (hopefully as an exception among all algorithms). Objections?

**Comment by sylvainschmitt** [comment]
Any it's great

**Comment by lukasbaumbach** [comment]
included in new version
