### ISSUE TITLE
using SSDM

### ISSUE THREAD

**Issue by lwind18** [sylvainschmitt/SSDM#68]
When I load the occurrence data, the error came up with:
"subscript out of bounds"
But I double checked the occurrence data, it is inside of the raster data.
Does anyone have the similar question? Or how do I fix this?
Thanks.

**Comment by sylvainschmitt** [comment]
You'll need to be clearer, could you provide a summary of both your occurrences and your environmental layers with `summary` ? And have you checked that you correctly set parameters of the `load_occ` function ?

**Comment by lwind18** [comment]
I use load_var to read the environmental variables.  
After I summary (), I got the error:
summary(clienv)
Error in apply(object@data@values, 2, quantile, na.rm = TRUE) : 
  no slot of name "data" for this object of class "RasterStack"
Then I cleared the occurrence data again and after I load_occ, I still got the error:
occ <- load_occ(path = setwd("XXX"),
+                    clienv, 
+                    file = "data.csv", 
+                    Xcol = "longtitude", Ycol = "latitude", Spcol = "species")
Error in Env@layers[[1]] : subscript out of bounds.

**Comment by lwind18** [comment]
Ok, this time, after I load_var, I add one more line:
clienv <- load_var(path = setwd("XXX"), 
                   files = NULL, 
                   format = c(".tif"), 
                   Norm = TRUE)
clienv
Then I can get output like your code in the https://cran.r-project.org/web/packages/SSDM/vignettes/SSDM.html
Then after I load_occ, it give me other error:
Occurrences loading 
Error in .xyValues(x, as.matrix(y), ...) : xy should have 2 columns only.
Found these dimensions: 13247, 0.
I already deleted all other columns and just keep the species, longitude and latitude these three columns.
Thank you for you time.

**Comment by lwind18** [comment]
I figured it out, though I don't know why. This time, I remove the "Spcol", and it worked. Besides, I also tried summary, but I get the error:
summary(clienv)
Error in apply(object@data@values, 2, quantile, na.rm = TRUE) : 
  no slot of name "data" for this object of class "RasterStack"
If I just write code clienv, it gives me the information about environmental variables. I also noticed that sometimes, it gives me: 
clienv
class      : RasterStack 
nlayers    : 0

**Comment by lwind18** [comment]
I think it still has problem about running the whole code.
clienv <- load_var(path = setwd("XXXXXX"), 
                   files = NULL, 
                   format = c(".tif"), 
                   Norm = TRUE)
clienv

clienv0008 <- load_var(path = setwd("XXXXX"), 
                       files = NULL, 
                       format = c(".tif"), 
                       Norm = TRUE)
# load occurrence data
beeocc <- load_occ(path = setwd("XXXX"),
                   clienv, 
                   file = "bee.csv", 
                   Xcol = "longitude", Ycol = "latitude", sep = ",")
head(beeocc)
# an example for ensemble model (Apis mellifera)
bee1occ <- subset(beeocc, beeocc$species == "ApisMellifera")

ESDM <- ensemble_modelling(c('RF','SVM'), bee1occ, clienv0008, rep = 5, Xcol = "logitude",
                           Ycol = "latitude", name = "apismap0008", save = FALSE,
                           cv = "holdout", cv.param = c(0.8, 1), thresh = 1001,
                           metric = "SES", ensemble.metric = c('AUC'), ensemble.thresh = c(0.8),
                           PA = NULL)
plot(ESDM)
In this code, the apis meellifera has 56 records, but the code has been running 20 minutes and I still didn't get the result.

**Comment by lwind18** [comment]
My occurrence data has 13000 records. Today, I tried a small sample (1000 records) and it works till ensemble_modelling. But, when I am doing stack_modelling, it gives me error:
#### Ensemble models creation ##### 
Opening clusters, 1 cores 
Exporting environment to clusters 
Error in checkForRemoteErrors(val) : 
  one node produced an error: comparison of these types is not implemented
I am so sorry to bother you and thank you for your time.

**Comment by sylvainschmitt** [comment]
> Hey Sylvain,
Because using "stacking_modelling" still has problem, I am trying to using "stack" to get the richness map. It is working, but I don't know how to save the result. I can use plot to see the map, but if I want to save the map as GeoTIFF format, how could I do? Do you have code to support this?
I found there is "savePlot", is this one can be used for saving map?
Thank you for you time and this package is really helpful! (#69 closed for duplication)

`stacking_modelling` doesn't have a problem itself, you need to figure out what's happening in your specific case with your dataset. Anyway, if `stacking` is working great for you. And please before asking a question relative to the use of SSDM read the article, the manual, and the vignette. The `save.stack` function you are looking for is described in each of them.
