### ISSUE TITLE
how to save the result after using "stacking"

### ISSUE THREAD

**Issue by lwind18** [sylvainschmitt/SSDM#69]
Hey Sylvain,
Because using "stacking_modelling" still has problem, I am trying to using "stack" to get the richness map. It is working, but I don't know how to save the result. I can use plot to see the map, but if I want to save the map as GeoTIFF format, how could I do? Do you have code to support this? 
I found there is "savePlot", is this one can be used for saving map? 
Thank you for you time and this package is really helpful!

**Comment by sylvainschmitt** [comment]
Don't open multiple issues for the same question related to your use ! I'll answer on #68 .
