### ISSUE TITLE
Problem loading my own raster input

### ISSUE THREAD

**Issue by merel5541** [sylvainschmitt/SSDM#72]
Hi,
I am experiencing problems when I'm trying to load my own raster data sets. I first tried to load the data in .asc format since this was the original data I received. After that, I tried the .tiff format. I compared my data with your example data in ArcGIS and I can't find any differences. Your example data does work. 

I'm running the SSDM through the gui command. The error I get when trying to load the data is the following:

`Listening on http://127.0.0.1:3261
Error in .checkargs(path = path, files = files, format = format, categorical = categorical,  : 
  format parameter should be .grd, .tif, .asc, .sdat, .rst, .nc, .tif, .envi, .bil or .img`

my data is located on an external drive D:. Would it be possible that the location of the files is the problem? when I try to load the data I am able to do something with the categorical option. I can select one of the folder names of my external drive (in which the data is stored). The folder path for the data is: 
D:\INSECTENNETWERK\SSMD_input_WGS

the option I can choose in the categorical tab is the word INSECTENNETWERK.

I also tested with different coordinate systems to see if this was the issue, but I don't know which coordinate system the program accepts.

I also saw a suggestion to use the following type of code to download the SSDM:
`devtools::install_github("sylvainschmitt/SSDM", ref = "Forecasting-#42")`

This didn't solve the problem and gave me the following result with 2 errors and 1 warning:
` Installing package into ‘C:/Users/merel/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'SSDM' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices 
  converting help for package 'SSDM'
    finding HTML links ... done
    Algorithm.SDM-class                     html  
    Ensemble.SDM-class                      html  
    Env                                     html  
    Occurrences                             html  
    SSDM                                    html  
    Stacked.SDM-class                       html  
    ensemble                                html  
    ensemble_modelling                      html  
    evaluate                                html  
    gui                                     html  
    load.model                              html  
    load_occ                                html  
Rd warning: C:/Users/merel/AppData/Local/Temp/Rtmpim3eAa/R.INSTALL1b0c5cf1fd2/SSDM/man/load_occ.Rd:21: file link 'read.csv' in package 'utils' does not exist and so has been treated as a topic
    load_var                                html  
    mapDiversity                            html  
    modelling                               html  
    plot.model                              html  
    project                                 html  
    save.model                              html  
    stack_modelling                         html  
    stacking                                html  
    update-Stacked.SDM-method               html  
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
*** arch - i386
Error: package or namespace load failed for 'SSDM' in library.dynam(lib, package, package.lib):
 DLL 'caTools' not found: maybe not installed for this architecture?
Error: loading failed
Execution halted
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'C:/Users/merel/Documents/R/win-library/3.6/SSDM'
* restoring previous 'C:/Users/merel/Documents/R/win-library/3.6/SSDM'
Error: Failed to install 'SSDM' from GitHub:
  (converted from warning) installation of package ‘C:/Users/merel/AppData/Local/Temp/RtmpwhJPyB/file456c692e55eb/SSDM_0.2.6.9001.tar.gz’ had non-zero exit status`
I don't know if it's a fault in my data or in the way I'm using the model and I ran out of ideas to try.

**Comment by lukasbaumbach** [comment]
Hi! So the error you describe above sounds very much like #52 . 
Concerning the installation error: it looks very much like you don't have the package `caTools` installed (probably some dependency from one of the required packages). Please also check, if `utils` is properly installed. This is part of R core and it's very unusual to see warnings for it (I just checked and `read.csv` definitely still exists).

**Comment by lukasbaumbach** [comment]
closed, likely fixed in new version
