### ISSUE TITLE
CRAN packages requiring SDMTools

### ISSUE THREAD

**Issue by sylvainschmitt** [sylvainschmitt/SSDM#74]
> SDMtools has been unmaintained since 2014 and is formally orphaned: under the current CRAN policy other packages are not allowed to require it.

>And it needs attention: see https://cran.r-project.org/web/checks/check_results_SDMTools.html

>So either we need one of you to take over as maintainer or for all to move it to Suggests and use it conditionally (or remove it).

**Comment by sylvainschmitt** [comment]
We are only using `SDMTools` in `evaluate` to compute the optimal threshold. We might have to integrate the function into `SSDM` if `SDMTools` is removed from CRAN.

https://github.com/sylvainschmitt/SSDM/blob/f10c2c9302941e5abba0238032b0642d71ebe318/R/evaluate.R#L4

 The code is not to complicated: https://github.com/jjvanderwal/SDMTools/blob/master/R/optim.thresh.R

**Comment by lukasbaumbach** [comment]
Too bad... ok but what is the CRAN / Git policy for that? Do we ask jjvanderwal for permission to use the function or can we just include it in our repository with a reference to the author?

**Comment by sylvainschmitt** [comment]
If it's GPL we can integrate the code. We'll wait to see if somebody decide to take back code maintaining or to integrate the function in its package. And if not we'll add it in `SSDM` (in last option).

**Comment by sylvainschmitt** [comment]
> We have not received an offer, so please do proceed to update your packages (some of you already have, thank you).

We should include `SDMTools::evaluate` as an internal in `SSDM` and send a new version to CRAN. It could be the occasion to add some of your modifications to the new version. The deadline is **the 14th of February**.

**Comment by lukasbaumbach** [comment]
I agree this would be a good occasion to add some new things to CRAN. However, since my edits are not ready yet (algorithm arguments and flexible parallelization are still missing), we could only use one of the existing development branches, like Forecasting-#42. Maybe it would be preferable, though, to wait a little longer until the new version I'm working on is ready, since anything we prepare now would be a shortlived version anyways. 

Also, should I include the function or do you have free capacities for that? I'm fine either way.

**Comment by lukasbaumbach** [comment]
> We are only using `SDMTools` in `evaluate` to compute the optimal threshold. We might have to integrate the function into `SSDM` if `SDMTools` is removed from CRAN.
> 
> https://github.com/sylvainschmitt/SSDM/blob/f10c2c9302941e5abba0238032b0642d71ebe318/R/evaluate.R#L4
> 
> The code is not to complicated: https://github.com/jjvanderwal/SDMTools/blob/master/R/optim.thresh.R

@sylvainschmitt  actually we are using two functions, namely `optim.thresh` and `accuracy`. While `optim.thresh` is not too complex, `accuracy` - which currently delivers ALL of our evaluation criteria -  has a whole lot of depending functions from SDMTools (e.g. ``sensitivity`,specificity`, `auc`, etc.). 
So this will be a tricky one. How should we deal with it? Switch to a maintained package? The only ones that come to my mind are `PresAbs` (which is also old) and `sdm`.

**Comment by sylvainschmitt** [comment]
Does ` sdm`  deliver the same metrics ? I think I'll include ` optim.thresh`  in our code. `sensitivity`  and ` specificity`  can be computed by our own code (I think it's pretty simple). And maybe we can find another source for AUC.

**Comment by sylvainschmitt** [comment]
I'll just include all `SDMTools` code in the package for the moment as I have no time and we might do a better job in the future.

**Comment by lukasbaumbach** [comment]
Alright, that's probably the simplest solution for the moment!

**Comment by sylvainschmitt** [comment]
Shit I put the fix on the forecasting branch, I will thus merge it to the master.

**Comment by sylvainschmitt** [comment]
Package submitted to CRAN

**Comment by sylvainschmitt** [comment]
Similar issue with the package `gplots`  used for heatmaps to be replaced:

> Requires orphaned package: ‘gplots’

**Comment by lukasbaumbach** [comment]
When is the deadline? We might find a better replacement (maybe even base R) for that case.

**Comment by sylvainschmitt** [comment]
The 15th for a new version. I'll fix it tomorrow. There is plenty of way to do heatmaps, and as the heatmaps are included in dynamic documents I was thinking to use `ggplot`  and `plotly` to do it.

**Comment by sylvainschmitt** [comment]
Ok I replaced the `gplots::heatmap.2`  function by a code using `ggplot2`:

https://github.com/sylvainschmitt/SSDM/blob/3e427c5dbe460a22642ce78c89843f48ec3d0074/R/plot.model.R#L690-L699

But it forced me to include new dependencies:

https://github.com/sylvainschmitt/SSDM/blob/3e427c5dbe460a22642ce78c89843f48ec3d0074/R/plot.model.R#L10-L12

Anyway, I think in the future I would like to have all plots under `ggplot2` as I'm used to it now, and I largely prefer the outputs, even for rasters (or include also `leaflet`  and `plotly`).

I'm running the tests and if everything is okay I'll try a second submission to CRAN.

**Comment by sylvainschmitt** [comment]
> Dear maintainer,
>
> thanks, package SSDM_0.2.7.tar.gz is on its way to CRAN.
>
> Best regards,
> CRAN teams' auto-check service
