### ISSUE TITLE
Model training default

### ISSUE THREAD

**Issue by lukasbaumbach** [sylvainschmitt/SSDM#77]
[EDITED]

Hi @sylvainschmitt 
By default the `modelling` function builds models with 100% of the supplied occurrence data. This happens irrespective of which `cv` (holdout, kfold or LOO cross validation) is chosen.

For the 'holdout' and 'kfold' strategies, evaluation statistics are computed by splitting the data into test and training through the `cv.param` argument, but still within the `project` function the final model is build with 100% of the given data. While it's not a bad approach trying to use as much data as possible to train better models, this step also forbids any post-hoc evaluation or post-processing of the models (such as calculating other evaluation criteria or running a recalibration).

Therefore I would like to suggest the following edits:

1. add a third element to the `cv.param` vector, which defines which occurrence data is to be used for final model training (i.e. for the model that is being returned). Options: 
- 'all' (use all data, set as default)
- 'holdout' (use the same data as for training the evaluation models (last iteration, if cv.param[2]>1). this option is intended to be used in combination with `cv=holdout` and `cv.param[2]=1`
- numeric (0-1) (use fraction of the data). this option enables using a custom data fraction for training the final model irrespective of the cv-method used (mainly for flexibility, right off the bat I can't think of a practical case where this option would be preferable).

2. store information on test and training data in the model@data slot by adding the column `train`(TRUE/FALSE) and write it to obj@data inside the `evaluate` function. This would also mean we need to edit `get_model` (for each algorithm!!!), so it only uses training data for model building.

**Comment by lukasbaumbach** [comment]
Update: added a new argument that controls the strategy used for final model training.

@sylvainschmitt any suggestion how we should name it? 
`training.strategy`?

P.S.: note for future reference: changing anything in the `@data` slot is a pain (thousands of appearances in other functions)!

**Comment by sylvainschmitt** [comment]
Let's try to think simply, this data set used for the model fit and projection. Training seems too much to refer to the evaluation stage to me. Anything in the literature ? I would say something like  `full.model.data`.

And I'm not surprised, as soon as I touch the core attributes from the SDM objects, even if they are simple, you are messing with the root of the code ! Sop let's hope that formal testing and code coverage will avoid us any bugs due to all implications of this change.

**Comment by lukasbaumbach** [comment]
well yes, it's hard to condense it in one term. "training", "building" and "fitting" a model more or less all describe the same process. models are fit, evaluated and possibly fit again with adjusted settings. 
so maybe something like `final.fitting.data` could also work. 

but honestly, as long as the argument name leads the user on the right track, any name would be fine. so yes, let's just use `full.model.data` for now

**Comment by sylvainschmitt** [comment]
Globally I agree that the term model don't mean much and should be avoided as possible. `final.fit.data` sounds great to me (I think you can drop the ing).

**Comment by lukasbaumbach** [comment]
Implemented for next package update
