### ISSUE TITLE
Maxent evaluation

### ISSUE THREAD

**Issue by lukasbaumbach** [sylvainschmitt/SSDM#78]
Maxent requires special attention in terms of evaluation, since it is presence only and the background points it uses are not synonymous to (pseudo-) absences. 

Currently, Maxent is evaluated the same way as the other algorithms: withheld test presences and test absences are compared to model predictions. However, since background points are intended to represent the whole range of environmental conditions rather than being pseudo-absences, using only a small subset of them for testing may lead to bad performance criteria. I stumbled upon this by looking at the original Maxent html output, which showed me a training AUC 0.1 higher than the corresponding `Algorithm.SDM@evaluation`. 

If I now checked with the `dismo::evaluate` function (there's example code specifically for Maxent), the test AUC was even above the original Maxent estimation. Btw, ENMTools is also using this function.

Concerning the recent discussion about the orphaned `SDMTools` package, I'd like to suggest two solutions:
1) keep the SDMTools code, adjust the evaluation part, so that Maxent model's are always trained and evaluated with 10000 bg points (if PA is not set anyways). This may correct the value a little.
2) exchange the SDMTools `accuracy` and `optim.thresh` with the corresponding `evaluate` and `threshold` functions from `dismo`

@sylvainschmitt : What do you think?

**Comment by sylvainschmitt** [comment]
Double agreement ! I thank you to keep me updated but regarding decision I'm now considering you more expert on the subject.

**Comment by lukasbaumbach** [comment]
Ok, thanks for your trust :)

For now I'll try to adapt the SDMTools input, since it's a quick fix. Let's see how much it changes the evaluation. 

In the long term, however, we should definitely think about switching from SDMTools to dismo's evaluation tools.

**Comment by lukasbaumbach** [comment]
Ok, the long term seems to come closer than expected. I just checked the `SDMTools::accuracy` code again and noticed it is taking a strange approach.  While the `SDMTools::auc` function (from the very same package!!!) uses observed values and continuous predictions, in the `accuracy` function all predictions are binarized with a given threshold (the one SSDM computes with `SDMTools::optim.thresh`) BEFORE computing the AUC. As I understand it, the AUC is then only covering one point in the ROC curve, i.e. that of the threshold, and may underestimate the area below the curve for other thresholds or more, the whole curve.

Thus, I will try and implement the `dismo::evaluate` function now. It should contain the same performance measures as are currently stored in the `sdm@evaluation` slot.

**Comment by lukasbaumbach** [comment]
Quick question regarding the migration to dismo: 
`SDMTools::optim.thresh` included more (and partly different) thresholding methods than `dismo::threshold` does. Should we keep the former (so the `metric` argument does not need to change) or also switch to `dismo::threshold` and offer all of their thresholds instead?

Also, since I don't find the term `metric` very informative, I would change it to something like `bin.thresh` (binarization threshold) or `thresh.stat` (statistic used as classification threshold).

**Comment by sylvainschmitt** [comment]
I would say more and more accurate is better, we should just try not to lose the users. Beware to the documentation, the threshold option is explained and detailed everywhere.

So yes let's move to `dismo::threshold` and rename the option `bin.thresh` **BUT** keep the older option too with a warning message explainging it's deprecated and it will be removed in further versions (to keep backward compatibility for the moment).
