### ISSUE TITLE
Is it possible to extract individual species present probabilities from species richness maps?

### ISSUE THREAD

**Issue by BettyBoyse** [sylvainschmitt/SSDM#80]
Dear Sylvain, 
I have been looking into your package to build S-SDMs to then investigate sampling strategies. This means I am not interested in species richness but more so the probability of occurrence for individual species at any particular site. Is there a way to extract this information from the species richness map or it is not possible? Any help would be much appreciated.
Best wishes,
Betty

**Comment by sylvainschmitt** [comment]
This is possible but unfortunately not implemented as a function opened to the user. In fact the `evaluate`  method for `SSDM` is doing it to assess community prediction. Have a look here and adapt the code to your case and you should be okay:

https://github.com/sylvainschmitt/SSDM/blob/6ed453e9b0705301f64d55826ba6a2072db5f842/R/evaluate.R#L450-L455
