### ISSUE TITLE
Saving the SDM plot as raster layer

### ISSUE THREAD

**Issue by biswasdibyendu** [sylvainschmitt/SSDM#81]
Dear Sylvain,
I am using the SSDM package for the distribution of vulture. The SDMs are being saved in TIFF. 
**But I want to save it as a raster layer (with co-ordinate information and cell values) so that I can use it in the applications of GIS.**
Is there any possibility to do so?

Best regards!
Dibyendu.

**Comment by sylvainschmitt** [comment]
Tiff is a raster format !!

https://www.earthdatascience.org/courses/earth-analytics/lidar-raster-data-r/introduction-to-spatial-metadata-r/

You can open it in Qgis, ArcGis other Gis or R.

**Comment by biswasdibyendu** [comment]
Thank You for your response!
But it seems that while saving the SDM plot in TIFF format it is only being saved as an image in TIFF, not as a Geotiff (with coordinates information and cell values/ attributes). 

Therefore, it is not opening as a raster layer in ArcGIS or in R. 
I need to classify the SDM plot and therefore it is imperative to save it as in editable raster format.
Hope, I made my confusion placed clearly. 
![arcgis](https://user-images.githubusercontent.com/60889962/79745256-89f84800-8325-11ea-8365-91656239578e.jpg)
