### ISSUE TITLE
SDM cannot be saved as raster - issue not solved

### ISSUE THREAD

**Issue by biswasdibyendu** [sylvainschmitt/SSDM#82]
Thank You for your previous response!
But it seems that while saving the SDM plot in TIFF format it is only being saved as an image in TIFF, not as a Geotiff (with coordinates information and cell values/ attributes). 

Therefore, it is not opening as a raster layer in ArcGIS or in R. 
I need to classify the SDM plot and therefore it is imperative to save it as in editable raster format.
Hope, I made my confusion placed clearly. 
![arcgis](https://user-images.githubusercontent.com/60889962/79745256-89f84800-8325-11ea-8365-91656239578e.jpg)

_Originally posted by @biswasdibyendu in https://github.com/sylvainschmitt/SSDM/issues/81#issuecomment-616480542_

**Comment by biswasdibyendu** [comment]
Eventually got to resolve the issue. 
Many thanks.

**Comment by sylvainschmitt** [comment]
Why did you opened an issue whereas it is exactly the issue #81 ?
