### ISSUE TITLE
How to get the ROC plot ?

### ISSUE THREAD

**Issue by biswasdibyendu** [sylvainschmitt/SSDM#83]
How to get the ROC plots for different algorithms?

**Comment by sylvainschmitt** [comment]
Please read the package documentation before opening issues. Nothing mention ROC plot in the manual as we didn't implement it in the package. You'll have to built them manually from model evaluation. A quick google search give me that : https://rviews.rstudio.com/2019/03/01/some-r-packages-for-roc-curves/ .
