### ISSUE TITLE
Binary threshold and reclassification of projection raster

### ISSUE THREAD

**Issue by lukasbaumbach** [sylvainschmitt/SSDM#84]
This might be a serious flaw. In the final step of model projection, the output raster is reclassified into the range 0-1. This means, that the threshold used to produce the binary map becomes useless at this point! Additionally, while all values below 0 are reclassified/clamped to zero, for the upper limit this procedure is not repeated. Instead, the raster is reclassified based on the maximum value, which - if it is an outlier - may lead to very low suitability values. 

On a further note, since the data is being transformed due to the normalization, it cannot be compared to other projections anymore.

If we nevertheless want to keep the normalization, we should at least update the binarization threshold, too. 
Personally, however, I would strongly prefer clamping the maximum to 1. It is very unlikely to affect many values (and if it does, we can give out a warning). Plus, it's only consequent if the lower limit is already clamped.

See this example from a MARS model (norm is the current `@projection`, norm_bin the current `@binary`), threshold was ~0.23:
![raw_norm_clamp](https://user-images.githubusercontent.com/25368672/80577172-bb989f80-8a06-11ea-89d9-ff4b2d70e999.png)

**Comment by sylvainschmitt** [comment]
Yep, let's do it quickly though, and push the correction to CRAN

**Comment by lukasbaumbach** [comment]
I already fixed it locally and will start a pull request later in the afternoon

**Comment by sylvainschmitt** [comment]
Great, did you wanted to include other things in the next CRAN version ? Because I feel it's a major bug and I would push it on CRAN quickly.

**Comment by lukasbaumbach** [comment]
Fixed in 0.2.8.9002
