### ISSUE TITLE
stack_modelling function fails when run in miniconda environment on HPC(centos)

### ISSUE THREAD

**Issue by msjimc** [sylvainschmitt/SSDM#85]
Hi,
I'm trying to run SSDM on the University's HPC in a miniconda3 environment running R3.6.3. All the packages load OK and the load_var(), load_occ(), modelling() and ensemble_modelling() function when used as shown in the manual (https://cran.r-project.org/web/packages/SSDM/vignettes/SSDM.html), 
 However, the SSDM <- stack_modelling(c('CTA', 'SVM'), Occurrences, Env, rep = 1, ensemble.thresh = 0, Xcol = 'LONGITUDE', Ycol = 'LATITUDE', Spcol = 'SPECIES', method = "pSSDM", verbose = FALSE) line fails with:
Warning: namespace ‘SSDM’ is not available and has been replaced
by .GlobalEnv when processing object ‘’
Error in ensemble_modelling(algorithms, Spoccurrences, Env, Xcol, Ycol,  : 
  could not find function "ensemble_modelling"
Could someone please suggest how I could correct this error.
Thanks in advance,
ian

**Comment by sylvainschmitt** [comment]
The error suggest you have overwritten the "ensemble_modelling" function from the SSDM package by your own function in the global environment. For instance have a look to namespaces or environments in R top understand what happened to you: http://adv-r.had.co.nz/Environments.html. Anyway, if I understood well your issue, calling `SSDM::ensemble_modelling` should fix it.

**Comment by msjimc** [comment]
Hi,
I'd tried using the explicit name and that didn't work. I'm not sure if anything is been overwritten as the R script runs in a fresh miniconda R environment each time it runs and the exact same script works in RStudio. The script is derived from copying and pasting the commands from the manual (https://cran.r-project.org/web/packages/SSDM/vignettes/SSDM.html). In RStudio there is no text regarding starting a new worker process. Is this multi-threaded and the transfer to the new threads ia losing the reference to SSDM? The error message is repeated 5 times, I wasn't sure if this was R retrying or possibly it failing on 5 threads.

**Comment by sylvainschmitt** [comment]
Ok thank you for the precise feedback. It seems that we might have an issue with environment export. Do you work using parallelization within SSDM or outside ? And wish version of SSDM are you using ? @lukasbaumbach made a lot of improvements on parallelization. @lukasbaumbach do you think a small bug about environments might be introduced in `stack_modelling` ?

**Comment by sylvainschmitt** [comment]
@msjimc did you tried in Rstudio with the exact same script than on cluster ? Check also package and dependencies versions. The best would be to have a minimal reproducible example to help us diagnose the issue.

**Comment by msjimc** [comment]
Hi, Looking in my library folder on the cluster, SSDM is version 0.2.8. All the dependences are the latest versions and were downloaded on 28/4/2020 except for the 'foreign' package which I manually installed using 'https://cran.r-project.org/src/contrib/Archive/foreign/foreign_0.8-74.tar.gz' as the current version was developed for R(>= 4.0.0)  and the environment is R3.6.3.  
The packages are running exactly as on the manual web page with no attempt to run it in parallel. 
I have attached the R script and the *.Rout generated as it ran.
I hope this helps.

[ssdm.r.txt](https://github.com/sylvainschmitt/SSDM/files/4554944/ssdm.r.txt)
[ssdm.r.Rout.txt](https://github.com/sylvainschmitt/SSDM/files/4554948/ssdm.r.Rout.txt)

**Comment by sylvainschmitt** [comment]
Thanks but it's hard to tell what's happening. I don't know if it's linked or not to the R version. Can you run interactive session on your cluster ? If so try to run it in an interactive session to better trace the error. Another thing you can try is to build two ESDM for two different species and to stack them with the stacking function (it's what stack_modelling function does). It might help us to identify where the error happen. Anyway the error seems restricted to a specific case. Another thing, try to activate parallelization to see if foreach is solving the issue by better handling environments.

**Comment by lukasbaumbach** [comment]
This seems strange to me. In the default setup, `stack_modelling` is not parallelized, but only runs as a lapply loop. So export of environment to workers should not be an issue. Plus, if you start your session with a fresh environment, conflicting namespaces should not exist...

However, there seem to be quite a few warnings and additional errors in your code, @msjimc, which make it hard to figure out what is exactly causing the problem. Here's maybe a few things to check first:
- I can not see where you assigned the object `Occurrences`, you always seem to use `Occ`
- Did `modelling` and `ensemble_modelling` (i.e. SDM/ESDM) work normally?
- It seems like the code is somehow ending up in the code section for parallel execution and is starting workers (how many though?). Can you please try `stack_modelling` again with specifically setting `cores=0`?
- parallelization works with the foreach package and should specifically export the raster and SSDM package to each worker. Please check if foreach works correctly

**Comment by sylvainschmitt** [comment]
Great that you issue is solved, but there is apparently a small bug as it shouldn't have happened in the first place.

**Comment by lukasbaumbach** [comment]
As of now I still could not figure out the source of the issue. If `cores=0` and `parmode='species'` (the defaults in `stack_modelling`), the code always first checks if `cores>0`. Since it isn't, this should always result in running the lapply loop and no environment exporting issues should arise in the first place...
