### ISSUE TITLE
issue to define categorical variable

### ISSUE THREAD

**Issue by BettyBoyse** [sylvainschmitt/SSDM#86]
Dear Sylvain, 

I have 14 continuous environmental variables and one categorical variable. The vignette shows that only continuous variables are normalised but even though I have specified substrate as a categorical variable it is still being normalised between 0-1 which I don't want. 

load_var(path = "C:/Users/betty/OneDrive/Documents/Leeds/Med Meta-analysis/Environmental_layers/env.var.2.EPSG3035", files = c("BO_bathymean_lonlat.tif", "BO2_carbonphytomean_ss_lonlat.tif", "BO2_carbonphytorange_ss_lonlat.tif", "BO2_chlomean_ss_lonlat.tif", "BO2_chlorange_ss_lonlat.tif", "BO2_ppmean_ss_lonlat.tif", "BO2_pprange_ss_lonlat.tif", "BO2_tempmean_ss_lonlat.tif", "BO2_temprange_ss_lonlat.tif", "MS_biogeo01_aspect_EW_5m_lonlat.tif", "MS_biogeo02_aspect_NS_5m_lonlat.tif", "MS_biogeo05_dist_shore_5m_lonlat.tif", "MS_biogeo06_bathy_slope_5m_lonlat.tif", "vesseldens.EPSG3035.originalres.tif", "substraterast.tif"), categorical = "substraterast")

Is there a way I can fix this? 

Look forward to hearing from you

Best wishes, 
Betty

**Comment by sylvainschmitt** [comment]
Have you looked to the name of your variables in the output ? Have you tried `categorical = "substraterast.tif"` for instance ?

**Comment by BettyBoyse** [comment]
Yes I have tried both variants, it did not make any difference

**Comment by sylvainschmitt** [comment]
You need to give more information. Additionally a categorical variable can't be normalized. Load less variables and give the code and the summary of the output.

**Comment by BettyBoyse** [comment]
environmental.variables <- load_var(path = "C:/Users/betty/OneDrive/Documents/Leeds/Med Meta-analysis/Environmental_layers/env.var.2.EPSG3035", files = c("BO_bathymean_lonlat.tif", "BO2_tempmean_ss_lonlat.tif", "substraterast.tif"), categorical = "substraterast.tif")

> environmental.variables
class      : RasterStack 
dimensions : 180, 635, 114300, 3  (nrow, ncol, ncell, nlayers)
resolution : 5920, 9250  (x, y)
extent     : 2922103, 6681303, 863802.7, 2528803  (xmin, xmax, ymin, ymax)
crs        : +proj=laea +lat_0=52 +lon_0=10 +x_0=4321000 +y_0=3210000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs 
names      : BO_bathymean_lonlat, BO2_tempmean_ss_lonlat, substraterast 
min values :         -1.83998136,             0.65601011,    0.07692308 
max values :                   1,                      1,                                  1 

substrate is created using an index 1:13

**Comment by sylvainschmitt** [comment]
Ok I see, the package thus converted the index into numeric before normalizing. So the `categorical` option is used here :
https://github.com/sylvainschmitt/SSDM/blob/d8152bd234e2553d393df40fd40834e585090d20/R/load_var.R#L121
And the raster name shouldn't include the file type. So it should be the same name as the name in `environmental.variables`. Have a look to `names(environmental.variables)` and check that it match exactly the categorical as you defined it. Should be thus:
```
environmental.variables <- load_var(path = "C:/Users/betty/OneDrive/Documents/Leeds/Med Meta-analysis/Environmental_layers/env.var.2.EPSG3035", files = c("BO_bathymean_lonlat.tif", "BO2_tempmean_ss_lonlat.tif", "substraterast.tif"), categorical = "substraterast")
```
Can you give the summary of this command ?

**Comment by BettyBoyse** [comment]
Sylvain, please find summary using categorical = "substraterast"

environmental.variables
class      : RasterStack 
dimensions : 180, 635, 114300, 3  (nrow, ncol, ncell, nlayers)
resolution : 5920, 9250  (x, y)
extent     : 2922103, 6681303, 863802.7, 2528803  (xmin, xmax, ymin, ymax)
crs        : +proj=laea +lat_0=52 +lon_0=10 +x_0=4321000 +y_0=3210000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs 
names      : BO_bathymean_lonlat, BO2_tempmean_ss_lonlat, substraterast 
min values :         -1.83998136,             0.65601011,    0.07692308 
max values :                   1,                      1,                       1

**Comment by sylvainschmitt** [comment]
Can you give all outputs (not just a piece) of:
```
environmental.variables <- load_var(path = "C:/Users/betty/OneDrive/Documents/Leeds/Med Meta-analysis/Environmental_layers/env.var.2.EPSG3035", files = c("BO_bathymean_lonlat.tif", "BO2_tempmean_ss_lonlat.tif", "substraterast.tif"), categorical = "substraterast")
names(environmental.variables)
summary(environmental.variables)
environmental.variables[[3]]
summary(environmental.variables[[3]])
```

**Comment by BettyBoyse** [comment]
names(environmental.variables)
[1] "BO_bathymean_lonlat"    "BO2_tempmean_ss_lonlat" "substraterast"  

> summary(environmental.variables)
        BO_bathymean_lonlat BO2_tempmean_ss_lonlat substraterast
Min.             -1.8399813           6.560101e-01  7.692308e-02
1st Qu.          -0.8663917           8.240486e-01  2.307692e-01
Median           -0.3010767           8.642166e-01  3.744935e-01
3rd Qu.          -0.1054937           9.253936e-01  8.461539e-01
Max.              1.0000000           1.000000e+00  1.000000e+00
NA's          90563.0000000           5.992500e+04  6.567400e+04

environmental.variables[[3]]
class      : RasterLayer 
dimensions : 180, 635, 114300  (nrow, ncol, ncell)
resolution : 5920, 9250  (x, y)
extent     : 2922103, 6681303, 863802.7, 2528803  (xmin, xmax, ymin, ymax)
crs        : +proj=laea +lat_0=52 +lon_0=10 +x_0=4321000 +y_0=3210000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs 
source     : C:/Users/betty/AppData/Local/Temp/RtmpIzxBxk/NumberOne/.rasters/substraterast.tif 
names      : substraterast 
values     : 0.07692308, 1  (min, max)

>summary(environmental.variables[[3]])
        substraterast
Min.       0.07692308
1st Qu.    0.23076923
Median     0.36479597
3rd Qu.    0.84615386
Max.       1.00000000
NA's       0.00000000

**Comment by sylvainschmitt** [comment]
If you are in a hurry you can also hack the code and load manually your substraterast with the raster package. Then downscale and crop it to the raster stack defintion. And finally join it to the raster stack :

```
environmental.variables <- load_var(path = "C:/Users/betty/OneDrive/Documents/Leeds/Med Meta-analysis/Environmental_layers/env.var.2.EPSG3035", files = c("BO_bathymean_lonlat.tif", "BO2_tempmean_ss_lonlat.tif"))
substraterast <- raster("C:/Users/betty/OneDrive/Documents/Leeds/Med Meta-analysis/Environmental_layers/env.var.2.EPSG3035/substraterast.tif")
substraterast <- raster::as.factor(substraterast)
substraterast <- aggregate(substraterast, fact = c((res(environmental.variables)[1]/res(substraterast)[1]),
                                           (res(environmental.variables)[2]/res(substraterast)[2])), fun = max)
substraterast <- crop(substraterast, extent(environmental.variables ))
environmental.variables <- stack(environmental.variables,substraterast)
```

**Comment by BettyBoyse** [comment]
I moved the substrate raster into its own folder and ran your code:

environmental.variables <- load_var(path = "C:/Users/betty/OneDrive/Documents/Leeds/Med Meta-analysis/Environmental_layers/test", categorical = "substraterast")

class      : RasterStack 
dimensions : 333, 752, 250416, 1  (nrow, ncol, ncell, nlayers)
resolution : 5000, 5000  (x, y)
extent     : 2923580, 6683580, 862253.7, 2527254  (xmin, xmax, ymin, ymax)
crs        : +proj=laea +lat_0=52 +lon_0=10 +x_0=4321000 +y_0=3210000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs 
names      : substraterast 
min values :             1 
max values :            13 

Now it works, but not if I include the other variables 

Thank you for the hack code

**Comment by sylvainschmitt** [comment]
You also didn't precise the filenames. And if you had a one continuous variable in the test folder ?

It seems that we have a little bug here and I would be glad if we can reproduce it in order to fix it.

**Comment by lukasbaumbach** [comment]
Hmm... I just tried with the SSDM example data and everything worked as intended. If I did not specify "SUBSTRATE" as categorical, it was normalized, too. So I have the feeling, this is system/path specific and one of the functions is leading to `names(Raster)` not being in `categorical`. Maybe the space in the path name is causing the problem?
