### ISSUE TITLE
negative variable importance

### ISSUE THREAD

**Issue by mathildehure** [sylvainschmitt/SSDM#91]
Hello,

I contact you because I realized several types of model with the same data (GLM, SVM, RF, etc.) and I wanted to make a modeling set of the best models (ESDM). It worked well but for the influence of the variables I get negative data for some variables and I don't know how to interpret it? No value is negative when the models are analyzed separately. Could you enlighten me on this?

Thank you for your help

**Comment by lukasbaumbach** [comment]
Hi,

hmm this is strange. In SSDM variable importance is calculated by in turns leaving out one variable, computing the correlation between predicted and observed and substracting this value from 1. The only way I can explain this behaviour, is that there is indeed a negative correlation between your predictions and observations, which results in negative variable importance. Why this is only the case in the ensemble remains a mystery to me though. I guess we would need a minimal working example to find out what's going on

**Comment by vlecours** [comment]
Hello,
I have the same issue where the variable importance reported is negative for some variables, and greater than 100% for some others. The sum of all percentages does amount to 100%. Any insights?
Thank you,
Vince

**Comment by lukasbaumbach** [comment]
Hi,

just from a quick look at the code, I noticed two things: 1) by default variable importance is derived from the Pearson correlation coefficient (which can be negative) and 2) after getting the coefficient for each variable, they are all normalized to sum to 100% (as far as I can tell). 
https://github.com/sylvainschmitt/SSDM/blob/d8152bd234e2553d393df40fd40834e585090d20/R/evaluate.axes.R#L12-L56

So my first guess would be, that once we have a negative correlation coefficient, it is carried through to the variable importance...
@sylvainschmitt maybe you can tell more precisely if this is a methodological or code implementation error?

**Comment by vlecours** [comment]
Thank you! I will wait for Sylvain's confirmation. In the meantime, how would you interpret such a pattern in percentage values? Using absolute values? 

For example, if Var1 has a variable importance value of -23% and Var2 has a variable importance value of +19%, Var1 would be more important than Var2? If so, implementing the absolute values within the normalization might be more intuitive for interpretation. 

Thank you!
Vince

**Comment by lukasbaumbach** [comment]
It's hard for me to tell without knowing the basics of this approach, best wait for Sylvain's answer ;)

**Comment by sylvainschmitt** [comment]
Hello and sorry for the late answer. I need to dive into the code but it seems that @lukasbaumbach is totally right. Still it seems weird that correlation can be negative, and I think the error come from the fact that we didn't expect that case (basically without the variable the model predict absence where presence were predicted by the full model and vice versa..). So I can correct the code to scale everything between 0-100 but it seems that your model has issues to give such a result.

**Comment by lukasbaumbach** [comment]
Checking the code again, I am not sure if I was right after all. If the `axes.metric` **is not** "Pearson", a negative value would be carried through (line 24-25). If it **is** "Pearson" on the other hand (default), the correlation coefficient is subtracted from 1 (`1-c`, line 35). Meaning, if we would have a perfect correlation (c=1) _without_ the variable, it's importance would be zero (1-1).

From this we may conclude, that in Vince's case the Pearson correlation coefficient was actually not negative, but larger than 1! In turn, if the coefficient had been negative, we would have seen an increased variable importance (this is also a strange case and should maybe print a warning, but I would argue that it would still correctly reflect, that the variable is very important). If I am correct this time, at least from a practical side it would be easiest to just clamp higher values to 1. Nevertheless the question should be asked, how the coefficient can be higher than 1 in the first place...
