### ISSUE TITLE
Error in  parallel processing

### ISSUE THREAD

**Issue by momeni133** [sylvainschmitt/SSDM#92]
Hello everyone,
Finally, I successfully loaded all environmental variables and the occurrence table (using GUI).
But when I run the models I receive the below error:

> Error in serialize(data, node$con) : error writing to connection
Warning in .local(obj, ...) :
  Argument 'metric' is deprecated and will be removed in future versions. Please consider using 'bin.thresh' instead.

I think it is something related to parallel processing. Any ideas for solving this?
Many thanks

**Comment by lukasbaumbach** [comment]
Hi, this could be related to temporary files being lost. Use tmp=TRUE or tmp="path/to/directory"  to write temporary files to disk.
