### ISSUE TITLE
Get P-values from variable.importance

### ISSUE THREAD

**Issue by biswasdibyendu** [sylvainschmitt/SSDM#94]
Dear Sylvain,
I am using this package for my analysis and found it very user friendly so far.
According to my literature review before the analysis I designed my statistical analysis in such a way which needs to do stepwise backward elimination with the help of log-likelihood ratio and compare between two models to make the model simplest. 
After going through the documentation I suppose that the package is using somewhat a similar process like this for variable importance with jackknife/ Pearson. 
Is it possible to get the P values of the difference which will help me in model fitting?
Any help will be appreciated.
Thank You.

**Comment by lukasbaumbach** [comment]
To my knowledge this is not directly possible. Maybe you could take the source code and modify it for your purpose, if I'm not mistaken it's in `evaluate.axes`

**Comment by sylvainschmitt** [comment]
> After going through the documentation I suppose that the package is using somewhat a similar process like this for variable importance with jackknife/ Pearson.

Not at all please read the article corresponding to the package : https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.12841
