### ISSUE TITLE
SSDM and pseudo-absence selection

### ISSUE THREAD

**Issue by lusignorelli** [sylvainschmitt/SSDM#95]
Dear Dr. Schmitt, 
I am currently using this package for my analysis and I intend to run an ensemble SDM. However, I would like to create two sets of Pseudo-absence, according to the algorithm choice. Is it possible? If not, is there another way that I can do it? 

sp.ensemble<- ensemble_modelling(c('MAXENT','RF'),
                                 EFILT,
                                 Env,
                                 Xcol = 'lon',
                                 Ycol = 'lat',
                                 rep= 1,
                                 PA= NULL,  # create two pseudo-absence dataset?
                                 cv= "k-fold",
                                 cv.param= c(10, 100),
                                 metric = "TSS",
                                 ensemble.metric = c("AUC"),
                                 ensemble.thresh = c(0.8),
                                 )

Thanks in advance!

**Comment by lusignorelli** [comment]
Actually I am running each model separately, using modelling(), and then I am applying an ensemble(). It is working for now.

**Comment by lukasbaumbach** [comment]
Hello, no this is not implemented in SSDM. You may either use a manual data set, which will be common for all algorithms used OR you use the defaults, which are algorithm-specific (but may be different from what you want). But as you correctly identified, the russian doll concept let's you individualize each method by running `modelling`, `ensemble` and `stacking` one after another.
