### ISSUE TITLE
Is it possible to convert models into S4 model objects? 

### ISSUE THREAD

**Issue by BettyBoyse** [sylvainschmitt/SSDM#96]
Dear Sylvain, 

I want to run models using the original packages i.e. maxent() function in dismo or randomForest() to give me more freedom over CV methods and pseudo absence selection. 

However, I want to then use the ensemble and stacked model functions for multiple species. Is this possible? 

Kind regards, 
Betty

**Comment by sylvainschmitt** [comment]
You can use all maxent and ranomForest parameters in all the modelling function from SSDM

**Comment by lukasbaumbach** [comment]
That's right. See the algorithm section in the `modelling` function or have a look at the vignette ('Advanced settings').
