### ISSUE TITLE
How improve species distribution models?

### ISSUE THREAD

**Issue by CarvalhoResearch** [sylvainschmitt/SSDM#97]
Hello Sylvain,  First of all, I would like to congratulate you and thank you for the wonderful SSDM package that has helped me in my master's research.  
I am using the 9 models in this package to obtain the current and future distribution of 39 plant species in Brazil, but unfortunately not all species have high suitability predictions according to various metrics (below I send figures), so a central question for me is whether starting from when models are acceptable and how can i improve them.   Thank you

![a](https://user-images.githubusercontent.com/53445986/89913324-f85d6080-dbc9-11ea-9a21-953dc52f9507.png)
![o](https://user-images.githubusercontent.com/53445986/89913371-057a4f80-dbca-11ea-9bf6-bc7f515edc7a.png)
![p](https://user-images.githubusercontent.com/53445986/89913399-0c08c700-dbca-11ea-909c-1330a5c6e018.png)
![s](https://user-images.githubusercontent.com/53445986/89913509-2f337680-dbca-11ea-9906-3048fc321c83.png)
![sp](https://user-images.githubusercontent.com/53445986/89913596-483c2780-dbca-11ea-9a79-107d1d362e98.png)
![t](https://user-images.githubusercontent.com/53445986/89913605-4bcfae80-dbca-11ea-900e-5173f5a1c087.png)

**Comment by sylvainschmitt** [comment]
I think we need to recommend you some methodological articles, any ideas of a good review @lukasbaumbach  ? But you do realize it is a large question, and you can start to do your own literature review on your side, as we offer a tool but not a methodological expertise.

**Comment by lukasbaumbach** [comment]
These two could be a good start:
Araujo et al (2019) Standards for distribution models in biodiversity assessments
Warren et al (2020) Evaluating species distribution models with discrimination accuracy is uninformative for many applications
