### ISSUE TITLE
Normalization issue in model projection

### ISSUE THREAD

**Issue by CarvalhoResearch** [sylvainschmitt/SSDM#98]
Hello Sylvain,  

I used fenv<-stack(paste("/home/eduardo/preditor/future/",list.files('/home/eduardo/preditor/future/',pattern=''),sep='')) to stack future enviromental variables and I projected using algoritm_projection <- project(algoritm,fenv), but some maps have filled the entire area, for me this result is strange. See the Figures (second map is future distribution).
![Anadenanthera_colubrina](https://user-images.githubusercontent.com/53445986/90522283-e9365f80-e141-11ea-890a-6f754d6f8095.png)
![Aspidosperma_multiflorum](https://user-images.githubusercontent.com/53445986/90522286-ea678c80-e141-11ea-9136-57be4a9ad6c7.png)
![Aspidosperma_pyrifolium](https://user-images.githubusercontent.com/53445986/90522287-ea678c80-e141-11ea-887b-2fb548a0efbf.png)
![Bauhinia_cheilantha](https://user-images.githubusercontent.com/53445986/90522289-eb002300-e141-11ea-9c4e-37b599b5d8c2.png)
![Bauhinia_pentandra](https://user-images.githubusercontent.com/53445986/90522290-eb98b980-e141-11ea-9bd2-a89328feb8ba.png)
![Caesalpinia_bracteosa](https://user-images.githubusercontent.com/53445986/90522292-eb98b980-e141-11ea-878c-fa9029a0f19f.png)
![Chloroleucon_dumosum](https://user-images.githubusercontent.com/53445986/90522295-ec315000-e141-11ea-97f2-3a39e3959702.png)
![Cnidoscolus_phyllacanthus](https://user-images.githubusercontent.com/53445986/90522297-ecc9e680-e141-11ea-8b58-5a9833c7fa2c.png)
![Combretum_leprosum](https://user-images.githubusercontent.com/53445986/90522299-ed627d00-e141-11ea-9df8-7d7e06e388d0.png)
![Commiphora_leptophloeos](https://user-images.githubusercontent.com/53445986/90522300-ed627d00-e141-11ea-881e-9e6b19ac9da8.png)
![Cordia_oncocalyx](https://user-images.githubusercontent.com/53445986/90522302-edfb1380-e141-11ea-8eaf-d69315211708.png)
![Erythroxylum_pungens](https://user-images.githubusercontent.com/53445986/90522304-ee93aa00-e141-11ea-8e1e-5aff7198c9ff.png)
![Libidibia_ferrea](https://user-images.githubusercontent.com/53445986/90522307-ee93aa00-e141-11ea-893e-480c931d3193.png)
![Licania_rigida](https://user-images.githubusercontent.com/53445986/90522310-ef2c4080-e141-11ea-9f36-aa5f1478bcde.png)
![Mimosa_caesalpiniifolia](https://user-images.githubusercontent.com/53445986/90522311-ef2c4080-e141-11ea-9fc6-685eb123f7e8.png)
![Mimosa_tenuiflora](https://user-images.githubusercontent.com/53445986/90522313-efc4d700-e141-11ea-9336-ad0176bbc197.png)
![Ziziphus_joazeiro](https://user-images.githubusercontent.com/53445986/90522316-f05d6d80-e141-11ea-8b11-b4313829db84.png)

**Comment by lukasbaumbach** [comment]
Hi,
such results can have a whole bunch of different reasons (strange model extrapolation behaviour, over-/underfitted models, errors in environmental data, etc.). To be able to help you, however, we need to see at least your call to the stack_/ensemble_/`modelling` function. 

Best

**Comment by CarvalhoResearch** [comment]
My functions are structured using default options for  the 9 algorithms (e.g.: GLM<- modelling('GLM',occ, env, Xcol = 'longitude', Ycol = 'latitude') and GBM <- modelling('GBM', occ, env, Xcol = 'longitude', Ycol = 'latitude')


follows the original script, 

[run_sdm.txt](https://github.com/sylvainschmitt/SSDM/files/5119486/run_sdm.txt)

Thank you!

**Comment by lukasbaumbach** [comment]
From your script it seems that you loaded your environmental variables with `load_var` and normalization (`Norm=TRUE`) for model training, but simply stacked your future conditions without normalization. As a side note, as your future values are probably much higher than the training value range (normalization converts to 0-1 range) the above projections already show you that your models are very liberal (maybe underfitted) and seem to have a linear response (higher variable values result in higher occurrence probability).
For the future I recommend you to always check your inputs first before you go down the rabbit hole of modelling.

**Comment by CarvalhoResearch** [comment]
Very good! it really was that. Now I'm getting a project, but another problem arose, future projections are very similar to current projections, is it because the models are too liberal (maybe underfitted) or because the environmental variables are very similar ?. Another question is why the model is underfitted and what can I do to fit the model.


thank you very much

**Comment by sylvainschmitt** [comment]
>Another question is why the model is underfitted and what can I do to fit the model.Another question is why the model is underfitted and what can I do to fit the model.

Have a look to previous issues:  How improve species distribution models? #97

**Comment by sylvainschmitt** [comment]
> Is it because the models are too liberal (maybe underfitted) or because the environmental variables are very similar ?

You're the one that can answer that, not us. Maybe it's a bit of both. But you have to check yourself variables correlations and the fit quality.

**Comment by sylvainschmitt** [comment]
> Very good! it really was that.

Ok so I'm closing this issue. By the way, thanks @lukasbaumbach to always be the first "at the frontline" for new issues.
